// Local drawing and image import; artwork is saved in the project as PNG atlases.
let artAtlas=null,artContext=null,artDisplay=null,artBase=null,artLoading=false,artPen=true,artStroke=null,artHistory=[],artLoadToken=0,artLast=[0,0],artChanged=false;
let artPart='torso';
let photoImage=null,photoPixels=null,photoCrop=null,photoFit=null,photoDrag=null;
for(const [id,label] of Object.entries(CharacterCatalog.paintParts)){const o=document.createElement('option');o.value=id;o.textContent=label;q('#bb-art-part').appendChild(o);}for(const [i,view] of CharacterArt.views.entries()){const o=document.createElement('option');o.value=i;o.textContent=view;q('#bb-art-side').appendChild(o);}
for(const key of ['outfit','hair','hat','glasses','back','held'])for(const value of CharacterCatalog.choices[key]){const o=document.createElement('option');o.value=value;o.textContent=value;q('#bb-photo-'+key).appendChild(o);}
function openArtPanel(){showCharacterStudio();q('#bb-character-panel').hidden=true;q('#bb-photo-panel').hidden=true;q('#bb-art-panel').hidden=false;q('#bb-art-part').value=q('#bb-art-part').value||'torso';q('#bb-art-side').value=q('#bb-art-side').value||'0';loadArtPart();}
function openPhotoPanel(){showCharacterStudio();q('#bb-character-panel').hidden=true;q('#bb-art-panel').hidden=true;q('#bb-photo-panel').hidden=false;for(const key of ['outfit','hair','hat','glasses','back','held'])q('#bb-photo-'+key).value=activeProfile()[key];if(!photoImage)drawPhoto();}
function atlasCanvas(){if(!artAtlas){artAtlas=document.createElement('canvas');artAtlas.width=384;artAtlas.height=256;artContext=artAtlas.getContext('2d',{willReadFrequently:true});artDisplay=q('#bb-art-canvas').getContext('2d');artBase=document.createElement('canvas');artBase.width=384;artBase.height=256;}return artAtlas;}
function currentArtFace(){const face=Number(q('#bb-art-side').value)||0;return {face,x:face%3*128,y:Math.floor(face/3)*128};}
function orientArt(){const f=currentArtFace().face;yaw=[0,Math.PI,-Math.PI/2,Math.PI/2,0,0][f];pitch=f===4?1.32:f===5?-1.32:.06;dirty=true;}
function ensurePaintablePart(part){const p=activeProfile(),change={};if(part==='hair'&&p.hair==='Bald')change.hair='Short';if(part==='hat'&&p.hat==='None')change.hat='Baseball cap';if(part==='back'&&p.back==='None')change.back='Backpack';if(part==='held'&&p.held==='None')change.held='Hammer';if(part==='cape'&&p.cape==='None')change.cape='Short cape';if(part==='glasses'&&p.glasses==='None')change.glasses='Round';if(part==='accessory'&&p.scarf==='None'&&p.neck==='None'&&p.ears==='None')change.scarf='Short scarf';if(part==='dress'&&p.outfit!=='Dress'&&!p.pants.toLowerCase().includes('skirt'))change.outfit='Dress';if(Object.keys(change).length){remember();activeCharacter().profile=CharacterCatalog.validate({...p,...change});syncCharacter();persist();}}
function syncArtChest(){const p=activeProfile();q('#bb-art-chest-controls').hidden=artPart!=='torso'||p.gender!=='Female';q('#bb-art-breast-mode').value=p.breastMode;q('#bb-art-breast-shape').value=p.breastShape;q('#bb-art-breast-size').value=p.breastSize;q('#bb-art-breast-value').textContent=p.breastSize;q('#bb-art-breast-size').setAttribute('aria-valuetext',p.breastSize+' of 150');q('#bb-art-nipple-controls').hidden=artPart!=='torso';q('#bb-art-nipple-style').value=p.nippleStyle;q('#bb-art-nipple-size').value=p.nippleSize;q('#bb-art-nipple-value').textContent=p.nippleSize;q('#bb-art-nipple-size').setAttribute('aria-valuetext',p.nippleSize+' of 100');q('#bb-art-nipple-color').value=p.nippleColor;}
for(const [id,key] of [['bb-art-breast-mode','breastMode'],['bb-art-breast-shape','breastShape'],['bb-art-nipple-style','nippleStyle']])for(const value of CharacterCatalog.choices[key]){const option=document.createElement('option');option.value=option.textContent=value;q('#'+id).appendChild(option);}
for(const [id,key] of [['bb-art-breast-mode','breastMode'],['bb-art-breast-shape','breastShape'],['bb-art-breast-size','breastSize'],['bb-art-nipple-style','nippleStyle'],['bb-art-nipple-size','nippleSize'],['bb-art-nipple-color','nippleColor']]){const input=q('#'+id),range=Object.hasOwn(CharacterCatalog.rangeFields,key),continuous=range||key==='nippleColor';input.addEventListener(continuous?'input':'change',()=>{if(artStroke!==null){syncArtChest();return;}if(artChanged)saveArt();const profile=CharacterCatalog.validate({...activeProfile(),[key]:range?Number(input.value):input.value});if(!input._undoSaved){remember();input._undoSaved=continuous;}activeCharacter().profile=profile;syncCharacter();persist();loadArtPart();});if(continuous)input.addEventListener('change',()=>{input._undoSaved=false;});}
function loadArtPart(){if(artChanged)saveArt();artStroke=null;characterRenderer.setLivePaint(null);atlasCanvas();const part=q('#bb-art-part').value;ensurePaintablePart(part);artPart=part;syncArtChest();const base=characterRenderer.appearanceAtlas(activeProfile(),part),baseContext=artBase.getContext('2d'),imageData=baseContext.getImageData(0,0,384,256);imageData.data.set(base.data);baseContext.putImageData(imageData,0,0);artChanged=false;artHistory=[];q('#bb-art-undo').disabled=true;artContext.clearRect(0,0,384,256);const data=activeProfile().paint?.[part],token=++artLoadToken;artLoading=!!data;if(data){const image=new Image();image.onload=()=>{if(token!==artLoadToken||q('#bb-art-panel').hidden)return;artLoading=false;artContext.clearRect(0,0,384,256);artContext.drawImage(image,0,0,384,256);characterRenderer.setLivePaint(artPart,artAtlas);drawArt();};image.onerror=()=>{if(token===artLoadToken){artLoading=false;q('#bb-art-message').textContent='This saved artwork could not be opened.';}};image.src=data;}if(!artLoading)characterRenderer.setLivePaint(artPart,artAtlas);drawArt();orientArt();q('#bb-art-message').textContent=(part==='torso'&&activeProfile().breastMode==='Comic'?'Comic chest uses ink lines and cel shading. Shape and size update live; draw over it to customize. ':part==='torso'&&activeProfile().breastMode==='Printed'?'Printed chest follows your shape and size. Draw over it to customize. ':'')+'Drawing on '+CharacterCatalog.paintParts[part]+'. Current colors and patterns are shown underneath. Erase or clear to reveal them.';}
function drawArt(){if(!artDisplay)return;const {x,y}=currentArtFace(),ctx=artDisplay;ctx.clearRect(0,0,256,256);for(let a=0;a<8;a++)for(let b=0;b<8;b++){ctx.fillStyle=(a+b)%2?'#243247':'#30415a';ctx.fillRect(a*32,b*32,32,32);}ctx.imageSmoothingEnabled=false;ctx.drawImage(artBase,x,y,128,128,0,0,256,256);ctx.drawImage(artAtlas,x,y,128,128,0,0,256,256);}
function artPoint(e){const b=q('#bb-art-canvas').getBoundingClientRect();return [(e.clientX-b.left)/b.width*128,(e.clientY-b.top)/b.height*128];}
function paintLine(a,b){const {x,y}=currentArtFace();artContext.save();artContext.beginPath();artContext.rect(x,y,128,128);artContext.clip();artContext.globalCompositeOperation=artPen?'source-over':'destination-out';artContext.strokeStyle=q('#bb-art-color').value;artContext.lineWidth=Number(q('#bb-art-size').value)||5;artContext.lineCap='round';artContext.lineJoin='round';artContext.beginPath();artContext.moveTo(x+a[0],y+a[1]);artContext.lineTo(x+b[0]+.001,y+b[1]);artContext.stroke();artContext.restore();artChanged=true;characterRenderer.setLivePaint(artPart,artAtlas);drawArt();}
function saveArt(record=true){if(!artChanged)return;const part=artPart,paint={...activeProfile().paint};const pixels=artContext.getImageData(0,0,384,256).data;let hasInk=false;for(let i=3;i<pixels.length;i+=4)if(pixels[i]){hasInk=true;break;}if(hasInk)paint[part]=artAtlas.toDataURL('image/png');else delete paint[part];const profile=CharacterCatalog.validate({...activeProfile(),paint});if(record)remember();activeCharacter().profile=profile;characterRenderer.cachePaint(paint[part],artAtlas);characterRenderer.setLivePaint(artPart,artAtlas);artChanged=false;dirty=true;persist();q('#bb-art-undo').disabled=!artHistory.length;}
q('#bb-art-canvas').addEventListener('pointerdown',e=>{e.preventDefault();if(artStroke!==null||artLoading)return;atlasCanvas();artHistory.push(artAtlas.toDataURL('image/png'));if(artHistory.length>24)artHistory.shift();artStroke=e.pointerId;artLast=artPoint(e);q('#bb-art-canvas').setPointerCapture(e.pointerId);paintLine(artLast,artLast);});
q('#bb-art-canvas').addEventListener('pointermove',e=>{if(artStroke!==e.pointerId)return;e.preventDefault();const next=artPoint(e);paintLine(artLast,next);artLast=next;});
for(const ev of ['pointerup','pointercancel','lostpointercapture'])q('#bb-art-canvas').addEventListener(ev,e=>{if(artStroke!==e.pointerId)return;artStroke=null;try{saveArt();}catch(err){q('#bb-art-message').textContent=err.message;}});
q('#bb-art-part').addEventListener('change',loadArtPart);q('#bb-art-side').addEventListener('change',()=>{drawArt();orientArt();});q('#bb-art-pen').addEventListener('click',()=>{artPen=true;q('#bb-art-pen').setAttribute('aria-pressed','true');q('#bb-art-eraser').setAttribute('aria-pressed','false');});q('#bb-art-eraser').addEventListener('click',()=>{artPen=false;q('#bb-art-pen').setAttribute('aria-pressed','false');q('#bb-art-eraser').setAttribute('aria-pressed','true');});q('#bb-art-clear').addEventListener('click',()=>{atlasCanvas();artHistory.push(artAtlas.toDataURL('image/png'));const {x,y}=currentArtFace();artContext.clearRect(x,y,128,128);artChanged=true;saveArt();drawArt();});q('#bb-art-undo').addEventListener('click',()=>{if(!artHistory.length)return;const image=new Image();image.onload=()=>{artContext.clearRect(0,0,384,256);artContext.drawImage(image,0,0,384,256);artChanged=true;saveArt();drawArt();};image.src=artHistory.pop();});
function readLocalImage(file){return new Promise((resolve,reject)=>{if(!file||file.size>20*1024*1024||file.type&&!['image/jpeg','image/png','image/webp'].includes(file.type)){reject(Error('Choose a PNG, JPEG, or WebP image under 20 MB.'));return;}const reader=new FileReader();reader.onerror=()=>reject(Error('This image could not be read.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(Error('This image format could not be opened.'));image.onload=()=>resolve(image);image.src=reader.result;};reader.readAsDataURL(file);});}
q('#bb-art-import').addEventListener('click',()=>q('#bb-art-file').click());q('#bb-art-file').addEventListener('change',async e=>{try{const image=await readLocalImage(e.target.files?.[0]);atlasCanvas();artHistory.push(artAtlas.toDataURL('image/png'));const {x,y}=currentArtFace();artContext.drawImage(image,x,y,128,128);artChanged=true;saveArt();drawArt();}catch(err){q('#bb-art-message').textContent=err.message;}e.target.value='';});
q('#bb-paint-character').addEventListener('click',openArtPanel);q('#bb-photo-character').addEventListener('click',openPhotoPanel);q('#bb-photo-done').addEventListener('click',showCharacterStudio);q('#bb-art-done').addEventListener('click',()=>{try{artStroke=null;saveArt();artLoadToken++;artLoading=false;const saved=persist();characterRenderer.setLivePaint(null);showCharacterStudio();const message=saved?'Artwork saved to your character.':'Artwork applied. Device storage is full; use Save to download your project.';q('#bb-character-message').textContent=message;status(message);}catch(error){q('#bb-art-message').textContent=error.message;}});
function drawPhoto(){const ctx=q('#bb-photo-canvas').getContext('2d');ctx.clearRect(0,0,256,320);ctx.fillStyle='#243247';ctx.fillRect(0,0,256,320);if(!photoImage){ctx.fillStyle='#bfcee4';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText('Choose a photo to begin',128,160);return;}const scale=Math.min(256/photoImage.width,320/photoImage.height),x=(256-photoImage.width*scale)/2,y=(320-photoImage.height*scale)/2;photoFit={x,y,scale};ctx.drawImage(photoImage,x,y,photoImage.width*scale,photoImage.height*scale);if(photoCrop){ctx.strokeStyle='#8fe4c5';ctx.lineWidth=2;ctx.strokeRect(x+photoCrop.x*scale,y+photoCrop.y*scale,photoCrop.w*scale,photoCrop.h*scale);}}
q('#bb-photo-choose').addEventListener('click',()=>q('#bb-photo-file').click());q('#bb-photo-file').addEventListener('change',async e=>{try{const image=await readLocalImage(e.target.files?.[0]),scale=Math.min(1,1600/Math.max(image.width,image.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(image.width*scale));c.height=Math.max(1,Math.round(image.height*scale));const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,c.width,c.height);photoImage=c;photoPixels=ctx.getImageData(0,0,c.width,c.height).data;photoCrop={x:0,y:0,w:c.width,h:c.height};q('#bb-photo-apply').disabled=false;drawPhoto();q('#bb-photo-message').textContent='Drag a box around one person, or select an accessory and apply that region. Choose the matching shapes, then create.';}catch(err){q('#bb-photo-message').textContent=err.message;}e.target.value='';});
function photoPoint(e){const b=q('#bb-photo-canvas').getBoundingClientRect();return [Math.max(0,Math.min(photoImage.width,((e.clientX-b.left)/b.width*256-photoFit.x)/photoFit.scale)),Math.max(0,Math.min(photoImage.height,((e.clientY-b.top)/b.height*320-photoFit.y)/photoFit.scale))];}
q('#bb-photo-canvas').addEventListener('pointerdown',e=>{if(!photoImage)return;e.preventDefault();q('#bb-photo-canvas').setPointerCapture(e.pointerId);photoDrag={id:e.pointerId,start:photoPoint(e)};});q('#bb-photo-canvas').addEventListener('pointermove',e=>{if(!photoDrag||photoDrag.id!==e.pointerId)return;e.preventDefault();const [x,y]=photoPoint(e),[a,b]=photoDrag.start;photoCrop={x:Math.min(x,a),y:Math.min(y,b),w:Math.abs(x-a),h:Math.abs(y-b)};drawPhoto();});for(const ev of ['pointerup','pointercancel','lostpointercapture'])q('#bb-photo-canvas').addEventListener(ev,()=>{photoDrag=null;});q('#bb-photo-reset').addEventListener('click',()=>{if(!photoImage)return;photoCrop={x:0,y:0,w:photoImage.width,h:photoImage.height};drawPhoto();});
async function makePhotoAtlas(part,crop,paint,stylized=true){const c=document.createElement('canvas');c.width=384;c.height=256;const ctx=c.getContext('2d',{willReadFrequently:true});if(paint[part])await new Promise(resolve=>{const img=new Image();img.onload=()=>{ctx.drawImage(img,0,0,384,256);resolve();};img.onerror=resolve;img.src=paint[part];});ctx.clearRect(0,0,128,128);ctx.drawImage(photoImage,crop.x,crop.y,crop.w,crop.h,0,0,128,128);if(stylized){const image=ctx.getImageData(0,0,128,128);image.data.set(CharacterArt.stylize(image.data));ctx.putImageData(image,0,0);}paint[part]=c.toDataURL('image/png');}
q('#bb-photo-apply').addEventListener('click',async()=>{if(!photoImage)return;const button=q('#bb-photo-apply');button.disabled=true;try{const crop=CharacterArt.rect(photoCrop,photoImage.width,photoImage.height),target=q('#bb-photo-target').value,analysis=CharacterArt.analyze(photoPixels,photoImage.width,photoImage.height,crop),old=activeProfile(),changes={};for(const key of ['outfit','hair','hat','glasses','back','held'])changes[key]=q('#bb-photo-'+key).value;let paint={...old.paint};if(target==='person'){if(q('#bb-photo-colors').checked)Object.assign(changes,analysis.palette);if(q('#bb-photo-face').checked)await makePhotoAtlas('head',analysis.rects.head,paint);if(q('#bb-photo-prints').checked){for(const part of ['torso','leftLeg','rightLeg','leftFoot','rightFoot'])await makePhotoAtlas(part,analysis.rects[part],paint);if(changes.outfit==='Dress')await makePhotoAtlas('dress',{x:crop.x+.17*crop.w,y:crop.y+.30*crop.h,w:.66*crop.w,h:.62*crop.h},paint);for(const part of ['hat','back','held'])if(changes[part]!=='None')await makePhotoAtlas(part,analysis.rects[part],paint);changes.pattern='Plain';}}else{const targets=target==='leftLeg'?['leftLeg','rightLeg']:target==='leftFoot'?['leftFoot','rightFoot']:[target];for(const part of targets)await makePhotoAtlas(part,crop,paint);if(q('#bb-photo-colors').checked){const color=CharacterArt.sample(photoPixels,photoImage.width,photoImage.height,crop),colorKey={head:'skinColor',hair:'hairColor',torso:'shirtColor',dress:'dressColor',leftLeg:'pantsColor',leftFoot:'shoeColor',hat:'hatColor',glasses:'glassesColor',back:'accessoryColor',held:'accessoryColor'}[target];if(colorKey)changes[colorKey]=color;}if(target==='hat'&&changes.hat==='None')changes.hat='Baseball cap';if(target==='back'&&changes.back==='None')changes.back='Backpack';if(target==='held'&&changes.held==='None')changes.held='Camera';if(target==='glasses'&&changes.glasses==='None')changes.glasses='Square';if(target==='hair'&&changes.hair==='Bald')changes.hair='Short';if(target==='dress')changes.outfit='Dress';}
 const profile=CharacterCatalog.validate({...old,...changes,paint});remember();activeCharacter().profile=profile;syncCharacter();persist();dirty=true;q('#bb-photo-message').textContent='Photo colors and prints applied. Rotate the 3D preview, adjust any shape, or select another region for an accessory.';}catch(err){q('#bb-photo-message').textContent=err.message;}finally{button.disabled=false;}});
