// Powers use swept brick casts, joint poses, and the ordinary repair ledger.
let heroOwner='',heroCooldown=0,heroPending=null,heroLift=null,heroConstruct=null,heroEmission=0;
const descendHeld=new Set(),frozenBricks=new Map();
let constructBag=[],lastConstruct='',heroShapeMeshes=null;
function nextConstruct(){if(!constructBag.length){constructBag=Object.keys(SuperPowers.constructs);for(let i=constructBag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[constructBag[i],constructBag[j]]=[constructBag[j],constructBag[i]];}if(constructBag.at(-1)===lastConstruct)[constructBag[0],constructBag[constructBag.length-1]]=[constructBag.at(-1),constructBag[0]];}return lastConstruct=constructBag.pop();}
function heroStatus(){const s=controller?.state||{};return {flying:!!s.flying,climbing:!!s.climbEnabled,speedBoost:Math.max(0,s.speedBoost||0),cooldown:heroCooldown,lifting:!!heroLift};}
function resetHero(clearIce=false){heroCooldown=0;heroPending=null;heroConstruct=null;descendHeld.clear();if(heroLift){makeDebris(heroLift.entry);heroLift=null;}if(controller){Object.assign(controller.state,{flying:false,flightCruise:0,flightTilt:0,climbEnabled:false,climbing:false,speedBoost:0,heroAction:null,heroTime:0});}if(clearIce){frozenBricks.clear();constructBag=[];for(const n of typeof npcs==='undefined'?[]:npcs)n.state.frozen=0;}}
function syncHero(){const p=activeProfile(),owner=activeCharacterId+'|'+p.power;if(owner!==heroOwner){resetHero();heroOwner=owner;}q('#bb-power').value=p.power;q('#bb-power-hint').textContent=SuperPowers.powers[p.power].hint;q('#bb-power-use').disabled=p.power==='None';q('#bb-power-use').textContent=SuperPowers.powers[p.power].action;q('#bb-power-use').setAttribute('aria-label',SuperPowers.powers[p.power].action+' · Q · '+SuperPowers.powers[p.power].hint);updateHeroHUD();}
function updateHeroHUD(){const s=controller?.state||{};q('#bb-descend').hidden=!s.flying;if(q('#bb-jump').textContent!==(s.flying?'Rise':'Jump'))q('#bb-jump').textContent=s.flying?'Rise':'Jump';q('#bb-power-use').setAttribute('aria-pressed',String(!!(s.flying||s.climbEnabled||s.speedBoost>0)));const action=heroLift?'Throw creation':s.flying?'Land':s.climbEnabled?'Release climb':s.speedBoost>0?'Stop boost':SuperPowers.powers[activeProfile().power].action,status=heroLift?'Lifted':s.flying?'Flying':s.climbEnabled?'Climb ready':s.speedBoost>0?Math.ceil(s.speedBoost)+'s':heroCooldown>0?'Recovering':'Ready';if(q('#bb-power-use').textContent!==action)q('#bb-power-use').textContent=action;if(q('#bb-power-status').textContent!==status)q('#bb-power-status').textContent=status;}

function equipPower(name){if(!SuperPowers.powers[name])throw Error('Unknown superpower.');if(activeProfile().power===name)return;remember();activeCharacter().profile=CharacterCatalog.validate({...activeProfile(),power:name});cancelRebuild();syncCharacter();persist();canvas.focus({preventScroll:true});dirty=true;}
for(const name of Object.keys(SuperPowers.powers)){const o=document.createElement('option');o.value=name;o.textContent=name;q('#bb-power').appendChild(o);}q('#bb-power').addEventListener('change',e=>equipPower(e.target.value));
q('#bb-power-use').addEventListener('pointerdown',e=>{e.preventDefault();if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))document.activeElement.blur();usePower();});q('#bb-power-use').addEventListener('click',e=>{if(!e.detail)usePower();});
q('#bb-descend').addEventListener('keydown',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();descendHeld.add('keyboard');}});q('#bb-descend').addEventListener('keyup',()=>descendHeld.delete('keyboard'));q('#bb-descend').addEventListener('blur',()=>descendHeld.delete('keyboard'));
q('#bb-descend').addEventListener('pointerdown',e=>{e.preventDefault();q('#bb-descend').setPointerCapture?.(e.pointerId);descendHeld.add(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])q('#bb-descend').addEventListener(event,e=>descendHeld.delete(e.pointerId));
function heroMovement(input,dt,cameraYaw,viewPitch=0){const s=ensurePhysics().state,p=activeProfile().power;let climbing=false;
 if(s.climbEnabled){if(input.jump){s.climbEnabled=false;s.vy=9.5;s.grounded=false;}else if(input.z>0){const d=[Math.sin(s.heading),0,Math.cos(s.heading)],hit=GameWeapons.cast([s.x,s.y+2,s.z],d,1.8,pieces,GamePhysics.bounds);climbing=!!hit&&hit.piece.y>0;}}
 s.climbing=climbing;let move={...input};if(s.flying){const x=input.x||0,z=(input.z||0)*Math.cos(viewPitch),vertical=(input.vertical||0)-(input.z||0)*Math.sin(viewPitch),norm=Math.max(1,Math.hypot(x,z,vertical));move={...move,x:x/norm,z:z/norm,vertical:vertical/norm,flightSpeed:input.run?26:16};const horizontal=Math.hypot(x,z),blend=1-Math.exp(-dt*7),tilt=Math.max(-.65,Math.min(.65,Math.atan2(vertical,horizontal||.001))),cruise=Math.min(1,horizontal/.65);s.flightTilt=(s.flightTilt||0)+(tilt-(s.flightTilt||0))*blend;s.flightCruise=(s.flightCruise||0)+(cruise-(s.flightCruise||0))*blend;}controller.step({...move,flight:s.flying,climbing,vertical:s.flying?move.vertical||0:climbing?1:0,speedScale:s.speedBoost>0?6:1,jumpSpeed:p==='Super jumping'?19:9.5},dt,cameraYaw);return s;
}
function heroAim(range=24,originOverride=null){const s=controller.state,origin=originOverride||[s.x,s.y+2.8*CharacterCatalog.heightScale(activeProfile()),s.z],front=[Math.sin(s.heading),0,Math.cos(s.heading)];let target=null,rank=Infinity;
 for(const p of pieces){if(p.y===0)continue;const b=GamePhysics.bounds(p),point=[(b.x0+b.x1)/2,Math.max(b.y0+.1,Math.min(b.y1-.1,s.y+2.6*CharacterCatalog.heightScale(activeProfile()))),(b.z0+b.z1)/2],delta=point.map((v,k)=>v-origin[k]),along=delta[0]*front[0]+delta[2]*front[2],across=Math.abs(delta[0]*front[2]-delta[2]*front[0]),distance=Math.hypot(...delta);if(along>.3&&distance<range&&across<.65+along*.10&&distance<rank){rank=distance;target=point;}}
 const vector=target?target.map((v,k)=>v-origin[k]):front,length=Math.hypot(...vector),dir=vector.map(v=>v/Math.max(.001,length)),limit=Math.min(range,GameWeapons.edgeDistance(origin,dir,controller.area));return {origin,dir,hit:GameWeapons.cast(origin,dir,limit,pieces,GamePhysics.bounds),end:origin.map((v,k)=>v+dir[k]*limit)};
}
function heroBeam(a,b,color,width=.06,life=.3){const delta=b.map((v,k)=>v-a[k]),length=Math.hypot(...delta);combatEffects.push({kind:'trace',position:a.map((v,k)=>(v+b[k])/2),length,heading:Math.atan2(delta[0],delta[2]),rx:-Math.atan2(delta[1],Math.hypot(delta[0],delta[2])),width,color,life,total:life});}
function heroBlast(point,radius,impulse=9){let count=0;const ids=pieces.filter(p=>p.y>0&&(()=>{const b=GamePhysics.bounds(p);return Math.hypot(Math.max(b.x0-point[0],0,point[0]-b.x1),Math.max(b.y0-point[1],0,point[1]-b.y1),Math.max(b.z0-point[2],0,point[2]-b.z1))<=radius;})()).map(p=>p.id);for(const id of ids){const p=pieces.find(p=>p.id===id);if(p){count+=breakHit(controller,p,{heading:controller.state.heading,impulse,mass:2}).smashed||0;if(count>=200)break;}}return count;}
function usePower(){if(!playing||conversation||gameOverlayOpen()||controller?.state.building)return {used:false};const s=ensurePhysics().state,power=activeProfile().power;if(power==='None')return {used:false};if(heroCooldown>0)return {used:false,cooldown:heroCooldown};cancelRebuild();pendingSmash=null;pendingSpell=null;
 if(power==='Flying'){s.flying=!s.flying;s.vy=s.flying?2:0;s.grounded=false;if(s.flying){pitch=0;s.flightCruise=0;s.flightTilt=0;}q('#bb-jump').textContent=s.flying?'Rise':'Jump';}
 else if(power==='Climbing'){s.climbEnabled=!s.climbEnabled;s.climbing=false;}
 else if(power==='Super speed'){s.speedBoost=s.speedBoost>0?0:8;}
 else if(power==='Super jumping'){if(s.grounded||s.coyote>0){s.vy=19;s.grounded=false;s.airTime=0;s.jumpBuffer=s.coyote=0;combatEffects.push(...GameMagic.burst('Thunder Bolt',[s.x,s.y+.2,s.z],true));heroCooldown=.5;}else return {used:false};}
 else if(power==='Read minds'){ensureNPCs();const n=NPCWorld.nearest(npcs,s,10);if(!n){gameMessage('No neighbor’s mind is within ten studs.',2);return {used:false};}const a=[s.x,s.y+3.8*CharacterCatalog.heightScale(activeProfile()),s.z],b=[n.state.x,n.state.y+3.8*CharacterCatalog.heightScale(n.profile),n.state.z],delta=b.map((v,k)=>v-a[k]),distance=Math.hypot(...delta),blocked=GameWeapons.cast(a,delta.map(v=>v/distance),distance,pieces,GamePhysics.bounds);if(blocked){gameMessage('Move into view of your neighbor to read their thoughts.',2);return {used:false};}clearInput();conversation=n;conversation.mindReading=true;q('#bb-conversation').hidden=false;q('#bb-npc-name').textContent=n.profile.name;q('#bb-npc-role').textContent='Mind reading · '+n.role;q('#bb-npc-speech').textContent='“'+(broken.length?'I hope someone rebuilds those broken creations.':{'Knight':'I wonder what lies beyond the castle walls.','Chef':'A brick oven would make this place feel like home.','Runner':'That open path would make a perfect racecourse.'}[n.role]||'I would love to build something new in the '+n.biome.replaceAll('_',' ')+'.')+'”';heroBeam(a,b,[.8,.5,1],.025,.7);s.heroAction='Read minds';s.heroTime=s.heroDuration=.7;heroCooldown=.5;}
 else if(power==='Telekinesis'){if(heroLift){if(heroLift.thrown)return {used:false};heroLift.thrown=true;heroLift.age=0;const aim=heroAim(24);const delta=(aim.hit?.point||aim.end).map((v,k)=>v-heroLift.position[k]),len=Math.hypot(...delta);heroLift.dir=delta.map(v=>v/Math.max(.001,len));heroLift.remaining=Math.min(24,len);s.heroAction='Telekinesis';s.heroTime=.45;s.heroDuration=.9;heroCooldown=.5;}else{const hit=heroAim(10).hit?.piece;if(!hit||hit.y===0){gameMessage('Face a creation within ten studs to lift it.',2);return {used:false};}const prior=broken.length;breakHit(controller,hit,{heading:s.heading,impulse:0,mass:0});const entry=broken[prior];if(!entry)return {used:false};const b=damagedBounds(entry);debris=debris.filter(d=>d.entryId!==entry.id);heroLift={entry,center:[(b.x0+b.x1)/2,(b.y0+b.y1)/2,(b.z0+b.z1)/2],position:[(b.x0+b.x1)/2,(b.y0+b.y1)/2+2,(b.z0+b.z1)/2],age:0,thrown:false};heroCooldown=.35;s.heroAction='Telekinesis';s.heroTime=s.heroDuration=.65;}}
 else{
  const kind=power==='Energy constructs'?nextConstruct():null,design=kind?SuperPowers.constructs[kind]:null,duration=power==='Claws'?.52:design?.duration||.65,contact=power==='Claws'?.18:power==='Strength'?.38:design?.contact||.23;
  heroCooldown=design?design.duration+.12:power==='Strength'?1:.65;heroPending={power,remaining:contact};s.heroAction=power;s.heroTime=s.heroDuration=duration;s.attack=power==='Claws'?.52:0;s.attackDuration=duration;s.attackWeapon='None';smashCooldown=Math.max(smashCooldown,duration);
  if(design){const aim=heroAim(design.range),target=aim.hit?.point||aim.end,confined=GamePhysics.containPoint(controller.area,target[0],target[2],2.5);target[0]=confined.x;target[2]=confined.z;const start=kind==='Anvil'?[target[0],target[1]+5,target[2]]:[s.x+Math.sin(s.heading)*1.2,s.y+(['Hammer','Sword'].includes(kind)?4.6:2.9)*CharacterCatalog.heightScale(activeProfile()),s.z+Math.cos(s.heading)*1.2];heroConstruct={kind,position:[...start],start,target,hitId:aim.hit?.piece.id,heading:s.heading,age:0};combatEffects.push(...GameMagic.burst('Verdant Vortex',start,true));}
 }

 updateHeroHUD();dirty=true;return {used:true,power,...heroStatus()};}
function releaseHeroAction(power){const s=controller.state,pose=CharacterModel.effectPose(s,activeProfile()),mouth=CharacterModel.transform(pose.head,[0,3.5-CharacterModel.pivots.head[1],.58]),aim=heroAim(['Freezing breath','Energy constructs'].includes(power)?8:26,power==='Freezing breath'?mouth:null),point=aim.hit?.point||aim.end;
 if(power==='Strength'){const at=[s.x,s.y+.7,s.z];heroBlast(at,3.5,14);combatEffects.push(...GameMagic.burst('Thunder Bolt',at));}
 if(power==='Claws'){const hit=controller.target(3.5);if(hit){breakHit(controller,hit,{heading:s.heading,impulse:6,mass:1});impactEffect([s.x+Math.sin(s.heading)*2,s.y+2.5*CharacterCatalog.heightScale(activeProfile()),s.z+Math.cos(s.heading)*2]);}const pose=CharacterModel.effectPose(s,activeProfile());for(const dx of [-.14,0,.14]){const tip=CharacterModel.transform(pose.rightForearm,[CharacterModel.handGrip(1)[0]+dx,CharacterModel.handGrip(1)[1]-.55,.20]),end=CharacterModel.transform(pose.rightForearm,[CharacterModel.handGrip(1)[0]+dx,CharacterModel.handGrip(1)[1]-.85,.20]);heroBeam(tip,end,[.8,.9,1],.025,.15);}}

 if(power==='Laser eyes'){const pose=CharacterModel.effectPose(s,activeProfile());for(const side of [-1,1]){const origin=CharacterModel.transform(pose.head,[side*.225,3.85-CharacterModel.pivots.head[1],.58]),delta=point.map((v,k)=>v-origin[k]),len=Math.hypot(...delta),dir=delta.map(v=>v/len),hit=GameWeapons.cast(origin,dir,len,pieces,GamePhysics.bounds);heroBeam(origin,hit?.point||point,[1,.12,.17],.055,.4);Object.assign(combatEffects.at(-1),{heroEye:side,heroTarget:hit?.point||point});if(hit&&hit.piece.y>0)breakHit(controller,hit.piece,{heading:s.heading,impulse:5,mass:.5});}combatEffects.push(...GameMagic.burst('Ember Burst',point,true));}
 if(power==='Freezing breath'){for(let i=1;i<=12;i++){const d=i/12*8,at=aim.origin.map((v,k)=>v+aim.dir[k]*d);if(aim.hit&&d>Math.hypot(...aim.hit.point.map((v,k)=>v-aim.origin[k]))+.1)break;const frost=GameMagic.trail('Frost Bloom',at,aim.dir,i*.1);for(const e of frost){e.position=e.position.map((v,k)=>at[k]+(v-at[k])*(1+d*.40));e.size*=1+d*.09;e.life=e.total=.5;}combatEffects.push(...frost);}if(aim.hit&&aim.hit.piece.y>0){const first=aim.hit.piece;for(const p of pieces){if(p.y===0)continue;const b=GamePhysics.bounds(p),near=Math.hypot(Math.max(b.x0-point[0],0,point[0]-b.x1),Math.max(b.y0-point[1],0,point[1]-b.y1),Math.max(b.z0-point[2],0,point[2]-b.z1))<=1.8;if(p.id===first.id||first.group&&p.group===first.group||near)frozenBricks.set(p.id,5);}combatEffects.push(...GameMagic.burst('Frost Bloom',point));}for(const n of npcs){const delta=[n.state.x-aim.origin[0],n.state.y+2*CharacterCatalog.heightScale(n.profile)-aim.origin[1],n.state.z-aim.origin[2]],len=Math.hypot(...delta),along=delta[0]*Math.sin(s.heading)+delta[2]*Math.cos(s.heading),across=Math.abs(delta[0]*Math.cos(s.heading)-delta[2]*Math.sin(s.heading));if(along>0&&len<8&&across<.8+along*.35&&!GameWeapons.cast(aim.origin,delta.map(v=>v/len),len,pieces,GamePhysics.bounds)){n.state.frozen=5;combatEffects.push(...GameMagic.burst('Frost Bloom',[n.state.x,n.state.y+2*CharacterCatalog.heightScale(n.profile),n.state.z],true));}}}
 if(power==='Energy constructs'&&heroConstruct){const c=heroConstruct,design=SuperPowers.constructs[c.kind];if(c.hitId&&pieces.some(p=>p.id===c.hitId))heroBlast(c.target,design.radius,design.impulse);combatEffects.push(...GameMagic.burst('Verdant Vortex',c.target));}
}
// Sweep every original brick volume, so a wide lifted build cannot slip
// past a wall merely because its center misses that wall.
function castHeroLift(l,distance){
 const bounds=damagedBounds(l.entry),offset=l.position.map((v,k)=>v-l.center[k]),delta=l.dir.map(v=>v*distance),candidates=pieces.filter(p=>{const b=GamePhysics.bounds(p);return b.x0<=bounds.x1+offset[0]+Math.max(0,delta[0])&&b.x1>=bounds.x0+offset[0]+Math.min(0,delta[0])&&b.y0<=bounds.y1+offset[1]+Math.max(0,delta[1])&&b.y1>=bounds.y0+offset[1]+Math.min(0,delta[1])&&b.z0<=bounds.z1+offset[2]+Math.max(0,delta[2])&&b.z1>=bounds.z0+offset[2]+Math.min(0,delta[2]);});let first=null;
 for(const p of l.entry.originals){const b=GamePhysics.bounds(p),half=[(b.x1-b.x0)/2,(b.y1-b.y0)/2,(b.z1-b.z0)/2],origin=[(b.x0+b.x1)/2+offset[0],(b.y0+b.y1)/2+offset[1],(b.z0+b.z1)/2+offset[2]],hit=GameWeapons.cast(origin,l.dir,first?.distance??distance,candidates,p=>{const b=GamePhysics.bounds(p);return {x0:b.x0-half[0],x1:b.x1+half[0],y0:b.y0-half[1],y1:b.y1+half[1],z0:b.z0-half[2],z1:b.z1+half[2]};});if(hit){const q=GamePhysics.bounds(hit.piece);hit.point=hit.point.map((v,k)=>Math.max([q.x0,q.y0,q.z0][k],Math.min([q.x1,q.y1,q.z1][k],v)));first=hit;}}
 return first;
}
function confineHeroLift(l){const b=damagedBounds(l.entry),area=controller.area,old=[...l.position];l.position[0]=Math.max(area.x0+l.center[0]-b.x0,Math.min(area.x1-(b.x1-l.center[0]),l.position[0]));l.position[2]=Math.max(area.z0+l.center[2]-b.z0,Math.min(area.z1-(b.z1-l.center[2]),l.position[2]));return Math.abs(old[0]-l.position[0])+Math.abs(old[2]-l.position[2])>.0001;}
function heroStep(dt){for(const [id,remaining] of frozenBricks){const next=remaining-dt;if(next<=.00001||!pieces.some(p=>p.id===id))frozenBricks.delete(id);else frozenBricks.set(id,next);}heroCooldown=Math.max(0,heroCooldown-dt);const s=controller.state;s.heroTime=Math.max(0,(s.heroTime||0)-dt);if(!s.heroTime)s.heroAction=null;if(heroLift&&!heroLift.thrown){s.heroAction='Telekinesis';s.heroTime=.5+Math.max(0,.5-heroLift.age);s.heroDuration=1;}for(const e of combatEffects)if(e.heroEye){const pose=CharacterModel.effectPose(s,activeProfile()),a=CharacterModel.transform(pose.head,[e.heroEye*.225,3.85-CharacterModel.pivots.head[1],.58]),delta=e.heroTarget.map((v,k)=>v-a[k]);e.position=a.map((v,k)=>(v+e.heroTarget[k])/2);e.length=Math.hypot(...delta);e.heading=Math.atan2(delta[0],delta[2]);e.rx=-Math.atan2(delta[1],Math.hypot(delta[0],delta[2]));}s.speedBoost=Math.max(0,(s.speedBoost||0)-dt);
 if(heroPending){heroPending.remaining-=dt;if(heroPending.remaining<=0){releaseHeroAction(heroPending.power);heroPending=null;}}
 if(heroConstruct){heroConstruct.age+=dt;const c=heroConstruct,design=SuperPowers.constructs[c.kind],t=Math.min(1,c.age/design.contact),u=c.kind==='Anvil'?t*t:t*t*(3-2*t),arc=['Hammer','Sword'].includes(c.kind)?1.2:0;c.position=c.start.map((v,k)=>v+(c.target[k]-v)*u+(k===1?Math.sin(t*Math.PI)*arc:0));if(heroConstruct.age>design.duration)heroConstruct=null;}
 if(heroLift){const lift=heroLift;lift.age+=dt;if(lift.thrown){const distance=Math.min(lift.remaining,18*dt),hit=castHeroLift(lift,distance);lift.position=lift.position.map((v,k)=>v+lift.dir[k]*(hit?.distance??distance));lift.remaining-=distance;const boundary=confineHeroLift(lift);if(hit||boundary||lift.remaining<=0||GameWeapons.edgeDistance(lift.position,lift.dir,controller.area)<.1){if(hit)heroBlast(hit.point,3,12);makeDebris(lift.entry,{heading:s.heading,impulse:9,mass:2});for(const d of debris.filter(d=>d.entryId===lift.entry.id)){d.x+=lift.position[0]-lift.center[0];d.y+=lift.position[1]-lift.center[1];d.z+=lift.position[2]-lift.center[2];GamePhysics.confineDebris(d,controller);}combatEffects.push(...GameMagic.burst('Arcane Spiral',lift.position));heroLift=null;}}else lift.position[1]=lift.center[1]+2+Math.sin(lift.age*2)*.18;}
 heroEmission+=dt;if(heroEmission>=.05){heroEmission=0;if(s.flying||s.speedBoost>0&&s.speed>.1)combatEffects.push(...GameMagic.trail(s.flying?'Prism Nova':'Thunder Bolt',[s.x,s.y+.4,s.z],[-Math.sin(s.heading),0,-Math.cos(s.heading)],s.phase));if(heroLift)combatEffects.push(...GameMagic.trail('Arcane Spiral',heroLift.position,[0,1,0],heroLift.age));for(const n of npcs)if(n.state.frozen>0)combatEffects.push(...GameMagic.trail('Frost Bloom',[n.state.x,n.state.y+1.8*CharacterCatalog.heightScale(n.profile),n.state.z],[0,1,0],n.state.frozen));}combatEffects=combatEffects.slice(-600);updateHeroHUD();
}
// Reusable smooth meshes for ice shells and solid green energy shapes.
function heroShapes(){if(heroShapeMeshes)return heroShapeMeshes;heroShapeMeshes={};const build=(name,make)=>{positions=[];normals=[];make();heroShapeMeshes[name]=upload();};build('cube',()=>box(0,0,0,1,1,1,.025));build('cylinder',()=>lathe(0,0,[[0,-.5],[.5,-.5],[.5,.5],[0,.5]]));build('cone',()=>lathe(0,0,[[0,-.5],[.5,-.5],[0,.5]]));build('sphere',()=>{const profile=[];for(let i=0;i<=20;i++){const angle=-Math.PI/2+i*Math.PI/20;profile.push([Math.cos(angle)*.5,Math.sin(angle)*.5]);}lathe(0,0,profile);});return heroShapeMeshes;}
function heroShape(shape,pos,size,color,rx=0,ry=0,rz=0,alpha=.65,additive=true,parent=null){const local=CharacterModel.matrix(...pos,ry,rx,rz);for(let c=0;c<3;c++)for(let r=0;r<3;r++)local[c*4+r]*=size[c];characterRenderer.effect(heroShapes()[shape],parent?CharacterModel.mul(parent,local):local,color,alpha,additive);}
function drawIceBox(b,remaining){const center=[(b.x0+b.x1)/2,(b.y0+b.y1)/2,(b.z0+b.z1)/2],size=[b.x1-b.x0+.20,b.y1-b.y0+.20,b.z1-b.z0+.20],fade=Math.min(1,remaining/.35);heroShape('cube',center,size,[.35,.78,.96],0,0,0,.16*fade,false);for(let axis=0;axis<3;axis++){const other=[0,1,2].filter(k=>k!==axis);for(const a of [-1,1])for(const d of [-1,1]){const pos=[...center],scale=[.035,.035,.035];pos[other[0]]+=a*size[other[0]]/2;pos[other[1]]+=d*size[other[1]]/2;scale[axis]=size[axis];heroShape('cube',pos,scale,[.66,.94,1],0,0,0,.55*fade);}}}
function drawConstruct(c){
 const design=SuperPowers.constructs[c.kind],t=Math.min(1,c.age/design.contact),swing=['Hammer','Sword'].includes(c.kind)?-1.1+1.7*t:0,appear=Math.min(1,c.age/.12),fade=Math.min(1,(design.duration-c.age)/.18),parent=CharacterModel.matrix(...c.position,c.heading,swing,0,appear),green=[.12,1,.35],light=[.35,1,.64],part=(shape,pos,size,color=green,rx=0,rz=0)=>heroShape(shape,pos,size,color,rx,0,rz,.58*fade,true,parent);
 if(c.kind==='Hammer'){part('cube',[0,0,0],[2.4,.85,1.1]);part('cylinder',[0,-1.3,0],[.25,2.3,.25],light);part('cube',[-1.25,0,0],[.18,.98,1.18],light);part('cube',[1.25,0,0],[.18,.98,1.18],light);}
 if(c.kind==='Fist'){part('cube',[0,0,0],[1.6,1.3,1.2]);for(const x of [-.6,-.2,.2,.6]){part('cube',[x,.20,.70],[.35,.85,.50],light);part('sphere',[x,.15,.98],[.38,.5,.3]);}part('cube',[-.92,-.23,.30],[.45,.8,.8],light);part('cylinder',[0,-.1,-.9],[.8,1.2,.8],light,Math.PI/2);}
 if(c.kind==='Sword'){part('cube',[0,.85,0],[.34,2.9,.14]);part('cone',[0,2.46,0],[.34,.40,.14],light);part('cube',[0,-.65,0],[1.4,.18,.32],light);part('cylinder',[0,-1.12,0],[.23,.75,.23],light);part('sphere',[0,-1.58,0],[.38,.35,.38]);}
 if(c.kind==='Anvil'){part('cube',[0,-.72,0],[2.2,.35,1.1],light);part('cube',[0,-.15,0],[.85,.9,.8]);part('cube',[0,.4,0],[2.35,.5,1.25],light);part('cone',[1.65,.35,0],[.9,1.3,.8],green,0,-Math.PI/2);}
 if(c.kind==='Rocket'){part('cylinder',[0,0,0],[.85,2.2,.85],light,Math.PI/2);part('cone',[0,0,1.65],[.85,1.1,.85],green,Math.PI/2);for(const x of [-1,1])part('cube',[x*.58,0,-.7],[.5,.12,.75]);for(const y of [-1,1])part('cube',[0,y*.58,-.7],[.12,.5,.75]);part('cone',[0,0,-1.3],[.45,.55,.45],light,-Math.PI/2);}
 if(c.kind==='Drill'){part('cube',[0,0,-.65],[1.2,1.1,1.3]);part('cone',[0,0,.9],[1.1,2.3,1.1],light,Math.PI/2);for(let i=0;i<8;i++){const angle=c.age*18+i*.9,r=.47*(1-i/10);part('sphere',[Math.cos(angle)*r,Math.sin(angle)*r,i*.22],[.19,.19,.19]);}}
}
function drawHeroEffects(){
 if(heroConstruct)drawConstruct(heroConstruct);
 if(heroLift){const l=heroLift;for(const p of l.entry.originals){const [w,d]=dims(p),pos=[p.x+w/2+l.position[0]-l.center[0],p.y*.4+height(p)*.2+l.position[1]-l.center[1],p.z+d/2+l.position[2]-l.center[2]];characterRenderer.effect(mesh(p),CharacterModel.matrix(...pos),rgb(p.color),.85);}}
 for(const p of pieces){const remaining=frozenBricks.get(p.id);if(remaining){const b=GamePhysics.bounds(p);b.y1+=p.kind==='tile'?0:.225;drawIceBox(b,remaining);}}
 for(const n of npcs)if(n.state.frozen>0){const pose=CharacterModel.jointPose(n.state,false,n.profile),parts=RigCollision.boxes(n.state.rigContact,pose,n.state,n.profile),min=[0,1,2].map(k=>Math.min(...parts.map(b=>b.min[k]))),max=[0,1,2].map(k=>Math.max(...parts.map(b=>b.max[k])));drawIceBox({x0:min[0],x1:max[0],y0:min[1],y1:max[1],z0:min[2],z1:max[2]},n.state.frozen);}
}
