let npcs=[],npcRevision=-1,conversation=null;
function ensureNPCs(){if(!pieces.length){npcs=[];controller?.setActors([]);return npcs;}if(!npcs.length)npcs=NPCWorld.populate(pieces,world,controller?.state||new GamePhysics.Controller(pieces,world).state);for(const n of npcs)characterRenderer.bindCollision(n.profile,n.controller);if(npcRevision!==renderRevision){NPCWorld.sync(npcs,pieces,world);npcRevision=renderRevision;}NPCWorld.connect(npcs,controller);return npcs;}
function npcData(){return NPCWorld.serialize(npcs);}
function resetNPCs(){npcs=[];npcRevision=-1;closeConversation();}
function restoreNPCs(saved){npcs=saved?NPCWorld.restore(saved,pieces,world):[];npcRevision=-1;closeConversation();}
function closeConversation(){if(conversation)conversation.mindReading=false;conversation=null;q('#bb-conversation').hidden=true;heldKeys.clear();touchMove.clear();rebuildHeld=false;if(playing)dirty=true;}
function talkToNPC(id=null){if(!playing)return null;ensureNPCs();const near=NPCWorld.nearest(npcs,controller.state),npc=id!==null?npcs.find(n=>n.id===id):near;if(!npc||Math.hypot(npc.state.x-controller.state.x,npc.state.z-controller.state.z)>3.7||Math.abs(npc.state.y-controller.state.y)>2.3){gameMessage('Walk closer to a neighbor, then press T or Talk.',2);return null;}clearInput();conversation=npc;conversation.mindReading=false;q('#bb-conversation').hidden=false;q('#bb-npc-name').textContent=npc.profile.name;q('#bb-npc-role').textContent=npc.role+' · '+npc.biome.replaceAll('_',' ');q('#bb-npc-speech').textContent=NPCWorld.reply(npc,'hello',world,environment,broken.length);npc.state.heading=Math.atan2(controller.state.x-npc.state.x,controller.state.z-npc.state.z);q('#bb-npc-input').value='';dirty=true;return {id:npc.id,name:npc.profile.name,speech:q('#bb-npc-speech').textContent};}
function askNPC(text){if(!conversation)return null;const speech=NPCWorld.reply(conversation,String(text).slice(0,160),world,environment,broken.length);q('#bb-npc-speech').textContent=speech;return speech;}
for(const [label,topic] of [['Who are you?','who are you'],['About this place','about this place'],['Building tips','building tips'],['Rebuilding','how to rebuild'],['Controls','run and jump']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>askNPC(topic));q('#bb-npc-topics').appendChild(b);}
q('#bb-talk').addEventListener('click',()=>conversation?closeConversation():talkToNPC());q('#bb-talk-close').addEventListener('click',closeConversation);q('#bb-npc-chat').addEventListener('submit',e=>{e.preventDefault();const input=q('#bb-npc-input');if(input.value.trim())askNPC(input.value.trim());input.value='';});
function npcFrame(dt){if(!playing||!controller)return;ensureNPCs();NPCWorld.step(npcs,dt,controller.state,conversation?.id||null);const near=NPCWorld.nearest(npcs,controller.state);q('#bb-talk').disabled=!near&&!conversation;q('#bb-talk').textContent=conversation?'Close talk':near?'Talk to '+near.profile.name:'Talk · T';if(conversation&&(Math.hypot(conversation.state.x-controller.state.x,conversation.state.z-controller.state.z)>(conversation.mindReading?10:4.5)||!conversation.mindReading&&!near))closeConversation();}
function registerNPCTools(register){register({name:'read_lego_neighbors',description:'Read the random LEGO NPCs, their positions and whether a conversation is within reach.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute(){ensureNPCs();return {neighbors:npcData(),nearest:controller?NPCWorld.nearest(npcs,controller.state)?.id||null:null};}});register({name:'talk_to_lego_neighbor',description:'Talk to a nearby LEGO NPC and ask about the world, building, controls or rebuilding. Requires the player to be within talking distance.',inputSchema:{type:'object',properties:{id:{type:'integer'},message:{type:'string',maxLength:160}},additionalProperties:false},execute(input){const npc=input.id===undefined?conversation:conversation?.id===input.id?conversation:null;if(!npc){const result=talkToNPC(input.id??null);if(!result)throw Error('Walk closer to this NPC first.');}const speech=input.message?askNPC(input.message):q('#bb-npc-speech').textContent;draw();return {id:conversation.id,name:conversation.profile.name,speech};}});}
