// Generated by scripts/extract-characters.mjs from v68's CharacterCatalog presets (P3.5).
import { hash64 } from '../../core/hash';

import { Character } from '../../core/schema';
import astronaut from './astronaut.json';
import balconyUnderwear from './balcony-underwear.json';
import beachSwimmer from './beach-swimmer.json';
import bikiniSet from './bikini-set.json';
import bodysuitLingerie from './bodysuit-lingerie.json';
import braletteAndBoyshorts from './bralette-and-boyshorts.json';
import bustierSet from './bustier-set.json';
import camisoleAndThong from './camisole-and-thong.json';
import chef from './chef.json';
import cityWorker from './city-worker.json';
import corsetAndBriefs from './corset-and-briefs.json';
import cosmicHeroine from './cosmic-heroine.json';
import cosmicVoyager from './cosmic-voyager.json';
import cowboy from './cowboy.json';
import crimsonHeroine from './crimson-heroine.json';
import crimsonVision from './crimson-vision.json';
import detective from './detective.json';
import emeraldGuardian from './emerald-guardian.json';
import emeraldHeroine from './emerald-heroine.json';
import explorer from './explorer.json';
import goldenWarrior from './golden-warrior.json';
import halterLingerie from './halter-lingerie.json';
import highWaistLingerie from './high-waist-lingerie.json';
import highWaistUnderwear from './high-waist-underwear.json';
import iceGuardian from './ice-guardian.json';
import knight from './knight.json';
import laceBodysuit from './lace-bodysuit.json';
import laceLingerie from './lace-lingerie.json';
import longlineLaceLingerie from './longline-lace-lingerie.json';
import longlineUnderwear from './longline-underwear.json';
import loungewear from './loungewear.json';
import microShortsOutfit from './micro-shorts-outfit.json';
import mindOracle from './mind-oracle.json';
import nightHuntress from './night-huntress.json';
import nightSentinel from './night-sentinel.json';
import pirate from './pirate.json';
import princess from './princess.json';
import rainforestGuide from './rainforest-guide.json';
import ribbonLingerie from './ribbon-lingerie.json';
import rockstar from './rockstar.json';
import runner from './runner.json';
import satinLingerie from './satin-lingerie.json';
import skier from './skier.json';
import skyJumper from './sky-jumper.json';
import solarChampion from './solar-champion.json';
import solarHeroine from './solar-heroine.json';
import speedHeroine from './speed-heroine.json';
import speedster from './speedster.json';
import sportMicroShortsSet from './sport-micro-shorts-set.json';
import starHeroine from './star-heroine.json';
import steelTitan from './steel-titan.json';
import stormHeroine from './storm-heroine.json';
import summerOutfit from './summer-outfit.json';
import thongLingerie from './thong-lingerie.json';
import triangleUnderwear from './triangle-underwear.json';
import wildClaw from './wild-claw.json';
import wildHeroine from './wild-heroine.json';
import wizard from './wizard.json';

const RAW: Record<string, unknown> = {
  astronaut: astronaut,
  'balcony-underwear': balconyUnderwear,
  'beach-swimmer': beachSwimmer,
  'bikini-set': bikiniSet,
  'bodysuit-lingerie': bodysuitLingerie,
  'bralette-and-boyshorts': braletteAndBoyshorts,
  'bustier-set': bustierSet,
  'camisole-and-thong': camisoleAndThong,
  chef: chef,
  'city-worker': cityWorker,
  'corset-and-briefs': corsetAndBriefs,
  'cosmic-heroine': cosmicHeroine,
  'cosmic-voyager': cosmicVoyager,
  cowboy: cowboy,
  'crimson-heroine': crimsonHeroine,
  'crimson-vision': crimsonVision,
  detective: detective,
  'emerald-guardian': emeraldGuardian,
  'emerald-heroine': emeraldHeroine,
  explorer: explorer,
  'golden-warrior': goldenWarrior,
  'halter-lingerie': halterLingerie,
  'high-waist-lingerie': highWaistLingerie,
  'high-waist-underwear': highWaistUnderwear,
  'ice-guardian': iceGuardian,
  knight: knight,
  'lace-bodysuit': laceBodysuit,
  'lace-lingerie': laceLingerie,
  'longline-lace-lingerie': longlineLaceLingerie,
  'longline-underwear': longlineUnderwear,
  loungewear: loungewear,
  'micro-shorts-outfit': microShortsOutfit,
  'mind-oracle': mindOracle,
  'night-huntress': nightHuntress,
  'night-sentinel': nightSentinel,
  pirate: pirate,
  princess: princess,
  'rainforest-guide': rainforestGuide,
  'ribbon-lingerie': ribbonLingerie,
  rockstar: rockstar,
  runner: runner,
  'satin-lingerie': satinLingerie,
  skier: skier,
  'sky-jumper': skyJumper,
  'solar-champion': solarChampion,
  'solar-heroine': solarHeroine,
  'speed-heroine': speedHeroine,
  speedster: speedster,
  'sport-micro-shorts-set': sportMicroShortsSet,
  'star-heroine': starHeroine,
  'steel-titan': steelTitan,
  'storm-heroine': stormHeroine,
  'summer-outfit': summerOutfit,
  'thong-lingerie': thongLingerie,
  'triangle-underwear': triangleUnderwear,
  'wild-claw': wildClaw,
  'wild-heroine': wildHeroine,
  wizard: wizard,
};

/** v68's character presets, as Character files (ids fixed per preset). */
export const BUILTIN_CHARACTERS: readonly Character[] = Object.entries(RAW).map(([slug, raw]) =>
  Character.parse({
    ...(raw as object),
    id: `chr_${(BigInt(`0x${hash64(`builtin:${slug}`)}`) % 36n ** 10n).toString(36).padStart(10, '0')}`,
  }),
);
