const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
let source=fs.readFileSync(path.join(__dirname,'maps.cjs'),'utf8').split('const b=ctx.boot(),el=')[0];source=source.replace('mapPlacing,controller}','mapPlacing,controller,undoCount:undoStack.length}');
const context={require,__dirname,console,AbortController,Blob,URL,setTimeout};vm.runInNewContext(source+';globalThis.boot=ctx.boot;',context);
const boot=context.boot,b=boot(),read=()=>JSON.parse(JSON.stringify(b.read())),manage=v=>b.tools.get('manage_lego_maps').execute(v),el=id=>b.elements['#'+id];
const anchor=read().maps.activeId,originalPieces=read().pieces,originalCharacters=read().characters;
const beforeUndo=b.qa.get().undoCount;
const result=manage({action:'generateRandom',count:4,seed:71153,size:16}).result,network=read().maps;
assert.equal(network.maps.length,5);assert.equal(result.mapIds.length,4);assert.equal(result.seed,71153);assert(network.links.length>=4);assert(network.links.every(l=>l.twoWay));assert.equal(b.qa.get().undoCount,beforeUndo+1,'whole batch is a single undo edit');assert.equal(b.qa.get().mapPreviewReturn,anchor,'preview return goes to the existing map');assert(!el('bb-map-preview').hidden);
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const worlds=network.maps.filter(m=>result.mapIds.includes(m.id)),signature=(save,ids)=>{const maps=save.maps.maps.filter(m=>ids.includes(m.id));return JSON.stringify(canonical(maps.map(m=>{const build=m.id===save.maps.activeId?save:m.build;return {name:m.name,spawns:m.spawns,pieces:build.pieces,world:{config:build.world.config,layoutVersion:build.world.layoutVersion,width:build.world.width,depth:build.world.depth},environment:build.environment,npcs:build.npcs};})));};
assert.equal(new Set(worlds.map(m=>(m.id===network.activeId?read():m.build).world.config.biomes[0])).size,4,'primary environments vary across the batch');assert.equal(new Set(worlds.map(m=>(m.id===network.activeId?read():m.build).world.config.seed)).size,4,'different terrain seeds');
const reachable=new Set([anchor]);for(let i=0;i<network.maps.length;i++)for(const l of network.links){if(reachable.has(l.from.mapId))reachable.add(l.to.mapId);if(reachable.has(l.to.mapId))reachable.add(l.from.mapId);}assert(result.mapIds.every(id=>reachable.has(id)),'no isolated generated maps');
const generatedSignature=signature(read(),result.mapIds);b.fire('bb-map-preview-back');assert.equal(read().maps.activeId,anchor);assert.deepStrictEqual(read().pieces,originalPieces,'existing terrain preserved');assert.deepStrictEqual(read().characters,originalCharacters,'character collection preserved');
b.fire('bb-undo');assert.equal(read().maps.maps.length,1);assert.equal(read().maps.links.length,0);b.fire('bb-redo');assert.equal(read().maps.maps.length,5);assert.equal(signature(read(),result.mapIds),generatedSignature,'redo restores identical maps');
const saved=JSON.stringify(read()),reload=boot(saved);assert.equal(reload.read().maps.maps.length,5);assert.equal(reload.read().maps.links.length,network.links.length,'links survive device reload');
function signatureEqual(a,b,label){const x=JSON.parse(a),y=JSON.parse(b),diff=[];function walk(a,b,p){if(diff.length>=6)return;if(a&&b&&typeof a==='object'&&typeof b==='object'){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))walk(a[k],b[k],p+'.'+k);}else if(a!==b)diff.push([p,a,b]);}walk(x,y,'maps');assert(diff.length===0,label+': '+JSON.stringify(diff));}
b.fire('bb-open');el('bb-data').value=saved;b.fire('bb-load-code');assert.equal(el('bb-dialog-message').textContent,'');signatureEqual(signature(read(),result.mapIds),generatedSignature,'project export/import preserves generated worlds');
const second=boot();const repeat=second.tools.get('manage_lego_maps').execute({action:'generateRandom',count:4,seed:71153,size:16}).result;assert.equal(signature(JSON.parse(JSON.stringify(second.read())),repeat.mapIds),generatedSignature,'seed reproduces terrain, weather, points and NPCs');assert.deepStrictEqual(JSON.parse(JSON.stringify(second.read().maps.links)),network.links,'seed reproduces connections');
for(const input of [{count:1},{count:16},{count:2,seed:-1},{count:2,seed:1.1},{count:2,biomes:[]},{count:2,biomes:['unknown']},{count:2,size:20},{count:12}]){const old=JSON.stringify(read());assert.throws(()=>manage({action:'generateRandom',seed:33,...input}));assert.equal(JSON.stringify(read()),old,'invalid batches are atomic');}
const restricted=manage({action:'generateRandom',count:2,seed:0,biomes:['mountains','volcanoes'],size:16}).result;for(const id of restricted.mapIds){manage({action:'switch',mapId:id});assert(read().world.config.biomes.every(v=>['mountains','volcanoes'].includes(v)));const point=read().maps.maps.find(m=>m.id===id).spawns[0];b.tools.get('explore_lego_world').execute({playing:true});b.qa.move(point);const c=b.qa.get().controller;assert(c.contains(point.x,point.z)&&c.clear(point.x,point.y,point.z),'generated arrival has room for complete actor rig: '+JSON.stringify({biomes:read().world.config.biomes,point,scenery:c.sceneryContacts(point.x,point.y,point.z).length,actors:c.actorContacts(point.x,point.y,point.z).length}));for(let i=0;i<80;i++)b.qa.tick(.025);assert(!el('bb-map-travel').hidden,'generated gate is usable');b.fire('bb-map-travel');assert.notEqual(read().maps.activeId,id,'travel reaches a linked map');assert(b.qa.get().playing);}
const ui=boot();ui.elements['#bb-random-count'].value='2';ui.elements['#bb-random-seed'].value='88';ui.elements['#bb-random-selected'].checked=true;ui.fire('bb-random-worlds');assert.equal(ui.read().maps.maps.length,3,'native button creates connected worlds');assert(ui.elements['#bb-map-message'].textContent.includes('Seed 88'));assert(ui.read().world.config.biomes.every(v=>['forest','mountains'].includes(v)),'native checkbox uses selected environments');
const limited=boot();limited.tools.get('manage_lego_maps').execute({action:'generateRandom',count:15,seed:47,biomes:['prairie'],size:16});assert.equal(limited.read().maps.maps.length,16);assert(limited.elements['#bb-random-worlds'].disabled,'capacity disables generation');const full=JSON.stringify(limited.read());assert.throws(()=>limited.tools.get('manage_lego_maps').execute({action:'generateRandom',count:2,seed:9}),/slots remain/);assert.equal(JSON.stringify(limited.read()),full);
console.log('PASS: seeded varied connected batches, two-way reachability, safe generated gates and travel, native controls/selected biomes, existing worlds/characters preserved, atomic validation/capacity, whole-batch undo/redo and full project/device persistence.');
