const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
let bootSource=fs.readFileSync(path.join(__dirname,'characters.cjs'),'utf8').split('const b=boot(),call=')[0];
bootSource=bootSource.replace("split('</script>')[0],context);", "split('</script>')[0].replace(/\\}\\)\\(\\);\\s*$/, 'globalThis.glowQA={guide:rebuildGuidance,direction:rebuildDirection,target:rebuildTarget,frame:gameFrame};})();'),context);").replace('return {tools,elements,buttons,buffers,stored,','return {qa:context.glowQA,tools,elements,buttons,buffers,stored,');
const ctx={require,__dirname,console,AbortController,Blob,URL,setTimeout};vm.runInNewContext(bootSource+'\nglobalThis.boot=boot;',ctx);
const b=ctx.boot(),call=(n,v)=>b.tools.get(n).execute(v),ground={id:1,x:-4,z:-4,y:0,rows:8,cols:8,turn:0,kind:'plate',color:3},tower=[1,4,7].map((y,i)=>({id:i+2,x:-1,z:-3,y,rows:2,cols:2,turn:0,kind:'brick',color:8,group:'target'})),original=[ground,...tower];
b.fire('bb-open');b.elements['#bb-data'].value=JSON.stringify({format:'brick-builder',version:4,pieces:original,npcs:[{id:1,profile:{},state:{x:-2,y:.4,z:2,heading:0}}]});b.fire('bb-load-code');assert.equal(b.elements['#bb-dialog-message'].textContent,'');call('explore_lego_world',{playing:true});call('control_lego_character',{smash:true});
call('control_lego_character',{forward:1,seconds:.4});
const position=()=>['x','y','z'].map(k=>b.read().player[k]),inside=position();
const suggested=b.qa.guide();assert(suggested&&Math.hypot(suggested.x-inside[0],suggested.z-inside[2])>.5,'a blocked position gets a visible nearby safe spot');
const arrow=b.qa.direction(suggested);assert(arrow&&arrow.entryId===suggested.entryId,'the arrow identifies the marked damaged creation');assert(arrow.x>=-1&&arrow.x<=1&&arrow.z>=-3&&arrow.z<=-1,'the arrow points directly into the original creation footprint');assert(Math.abs(Math.hypot(arrow.dx,arrow.dz)-1)<1e-9);
const physics={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../game-physics.js'),'utf8')+';globalThis.P=GamePhysics;',physics);const P=physics.P,scene=new P.Controller([ground]);
Object.assign(scene.state,{x:inside[0],y:inside[1],z:inside[2]});assert(P.rebuildSpot(scene,tower,suggested.x,suggested.z),'the suggested area is supported and clear of restored bricks');
assert(!P.rebuildSpot(scene,tower,0,-2),'a future brick footprint cannot glow as a valid spot');assert(!P.rebuildSpot(scene,tower,3.8,-2),'the marker cannot overhang a platform edge');
assert.equal(JSON.stringify(b.qa.guide()),JSON.stringify(suggested),'the guide remains stable while approaching');
call('control_lego_character',{rebuild:true,seconds:1.6});
assert.deepEqual(position(),inside,'rebuilding inside the restored footprint never teleports or respawns the character');
assert.equal(b.read().broken.length,1,'restoration waits until the player steps clear');assert.equal(b.elements['#bb-game-message'].textContent,'','visual guidance replaces the step-clear message');
call('control_lego_character',{right:1,seconds:.5});const outside=position();
call('control_lego_character',{rebuild:true,seconds:.35});const building=b.read().player;
assert(building.building&&building.buildBlend>.99&&building.buildTime>.1,'holding rebuild activates the animated building state');assert.deepEqual(position(),outside);
assert.equal(b.qa.direction(b.qa.guide()).entryId,b.qa.target().id,'the arrow remains bound to the active rebuild');
call('control_lego_character',{seconds:.025});assert.equal(b.read().player.building,false,'releasing rebuild stops the action');assert(b.elements['#bb-rebuild-track'].hidden,'an interrupted hold hides rebuild progress');
call('control_lego_character',{seconds:.3});assert.equal(b.read().player.buildBlend,0,'the building pose blends back to idle');
call('control_lego_character',{rebuild:true,seconds:.25});call('control_lego_character',{rebuild:true,jump:true,seconds:.025});assert(!b.read().player.building&&!b.read().player.grounded,'jumping interrupts building without restricting jump input');assert.equal(b.read().broken.length,1);
call('control_lego_character',{seconds:1.2});const settled=position();call('control_lego_character',{rebuild:true,seconds:1.5});
assert.deepEqual(position(),settled,'successful restoration preserves the exact player position');assert.equal(b.read().broken.length,0);assert.equal(b.qa.guide(),null,'the marker disappears immediately after restoration');
assert.deepEqual(JSON.parse(JSON.stringify(b.read().pieces)).sort((a,b)=>a.id-b.id),original,'rebuild restores every original brick exactly');
const load=obj=>{b.fire('bb-open');b.elements['#bb-data'].value=JSON.stringify({...obj,npcs:[{id:1,profile:{},state:{x:-5,y:.4,z:5,heading:0}}]});b.fire('bb-load-code');assert.equal(b.elements['#bb-dialog-message'].textContent,'');call('explore_lego_world',{playing:true});};
const wall=(id,x,z,w,d)=>({id,x,z,cols:Math.max(w,d),rows:Math.min(w,d),y:1,turn:d>w?1:0,kind:'brick',color:8}),walls=[wall(2,-2,-2,1,4),wall(3,1,-2,1,4),wall(4,-1,1,2,1)],door=[wall(5,-1,-2,2,1)];
const courtyard=[[-8,-8],[0,-8],[-8,0],[0,0]].map(([x,z],i)=>({...ground,id:101+i,x,z}));
load({format:'brick-builder',version:4,pieces:[...courtyard,...walls],broken:[{id:1,originals:door}],player:{x:0,y:.4,z:0,heading:Math.PI}});
const trappedPosition=position();call('control_lego_character',{rebuild:true,seconds:1.5});assert.equal(b.read().broken.length,1,'rebuild cannot seal the player into a newly closed pocket');assert.deepEqual(position(),trappedPosition,'enclosure prevention never moves the player');
const escapeGuide=b.qa.guide();assert(escapeGuide&&!P.rebuildTraps(new P.Controller([...courtyard,...walls]),door,escapeGuide.x,escapeGuide.z,escapeGuide.y),'the guide offers a standing position outside the future enclosure and inside the world border');
const other=[wall(8,3,-2,1,1)];
load({format:'brick-builder',version:4,pieces:courtyard,broken:[{id:1,originals:tower},{id:2,originals:other}],player:{x:0,y:.4,z:-2,heading:Math.PI}});
const firstGuide=b.qa.guide();assert.equal(firstGuide.entryId,1);const from=position();call('control_lego_character',{right:Math.sign(firstGuide.x-from[0]),seconds:Math.abs(firstGuide.x-from[0])/4});call('control_lego_character',{forward:-Math.sign(firstGuide.z-from[2]),seconds:Math.abs(firstGuide.z-from[2])/4});call('control_lego_character',{right:1,seconds:.05});
assert.equal(b.qa.guide().entryId,1,'approaching another damaged creation cannot switch the marker while standing in the original build area');call('control_lego_character',{rebuild:true,seconds:.25});assert.equal(b.qa.direction(b.qa.guide()).entryId,1,'the arrow points to the same creation that is actually rebuilding');
const model={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../character-model.js'),'utf8')+';globalThis.M=CharacterModel;',model);const M=model.M,point=(m,p)=>[0,1,2].map(k=>m[k]*p[0]+m[k+4]*p[1]+m[k+8]*p[2]+m[k+12]),close=(a,b)=>a.every((v,k)=>Math.abs(v-b[k])<.00002);
const handPath=[];let previous;
for(let t=0;t<=1.4;t+=.005){const pose=M.jointPose({grounded:true,buildBlend:Math.min(1,t*7),buildTime:t});
 for(const [child,parent] of Object.entries(M.parents))assert(close(point(pose[parent],M.pivots[child].map((v,k)=>v-M.pivots[parent][k])),point(pose[child],[0,0,0])),child+' stays connected while building');
 for(const [name,m] of Object.entries(pose)){assert(Array.from(m).every(Number.isFinite));if(previous)assert(Math.max(...Array.from(m).map((v,k)=>Math.abs(v-previous[name][k])))<.35,name+' moves continuously');}
 if(t>.15)handPath.push(point(pose.rightForearm,[.02,-.61,.06]));previous=pose;
}
assert(Math.max(...handPath.map(p=>p[1]))-Math.min(...handPath.map(p=>p[1]))>.25,'hands scoop and press through a visible vertical cycle');
assert(Math.max(...handPath.map(p=>p[2]))-Math.min(...handPath.map(p=>p[2]))>.3,'hands reach forward to assemble the bricks');
const idle=M.jointPose({}),work=M.jointPose({buildBlend:1,buildTime:.2});assert(work.root[13]<idle.root[13]-.08,'building bends the knees and lowers the body');
assert(close(point(M.jointPose({buildBlend:1,buildTime:.2},true).rightArm,[0,0,0]),M.pivots.rightArm),'character editing stays in the neutral pose');
console.log('PASS: rebuild arrows target the active creation and stay stable near competing damage; enclosure and overlap prevention preserve player position; exact restoration, connected building animation, release/jump cancellation.');
