const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
let source=fs.readFileSync(path.join(__dirname,'characters.cjs'),'utf8').split('const b=boot(),call=')[0];source=source.replace(".split('</script>')[0],context)",".split('</script>')[0].replace(/\\}\\)\\(\\);\\s*$/, 'globalThis.heroDebug=()=>({forceConstruct:kind=>{constructBag=[kind];},heroPending,heroLift,heroConstruct,frozenBricks,combatEffects,controller,npcs,conversation});globalThis.heroAPI={C:CharacterCatalog,M:CharacterModel,R:RigCollision,P:GamePhysics,S:SuperPowers};})();'),context)").replace('return {tools,elements,buttons,buffers,stored,','return {debug:context.heroDebug,api:context.heroAPI,tools,elements,buttons,buffers,stored,');source=source.replace(".split('<script>')[1]",".split('<script>')[1].replace('collisionParts,bindCollision};','collisionParts,bindCollision,inspect:p=>{build(p);return compiled;}};')");const bootCtx={require,__dirname,console,AbortController,Blob,URL,setTimeout};vm.runInNewContext(source+';globalThis.boot=boot;',bootCtx);const b=bootCtx.boot(),call=(n,v)=>b.tools.get(n).execute(v),{C,M,R,P,S}=b.api;
const ground=[];for(const x of [-16,-8,0,8])for(const z of [-16,-8,0,8])ground.push({id:100+ground.length,x,z,y:0,cols:8,rows:8,turn:0,kind:'plate',color:3});
const tower=(start,x,z,group,levels=4)=>Array.from({length:levels},(_,i)=>({id:start+i,x,z,y:1+i*3,cols:2,rows:2,turn:0,kind:'brick',color:8,group}));
function load(extra=[],neighbors=null,profile=C.defaults,player={x:0,y:.4,z:0,heading:Math.PI}){call('explore_lego_world',{playing:false});b.fire('bb-open');b.elements['#bb-data'].value=JSON.stringify({format:'brick-builder',version:4,pieces:[...ground,...extra],player,characters:{items:[{id:1,profile}],activeId:1},npcs:neighbors||[{id:1,profile:C.defaults,state:{x:10,y:.4,z:8,heading:0}}]});b.fire('bb-load-code');assert.equal(b.elements['#bb-dialog-message'].textContent,'');call('explore_lego_world',{playing:true});}
if(!process.env.HERO_FAST)for(const gender of ['Male','Female'])for(const costume of Object.keys(S.costumes)){const p=call('configure_lego_character',{profile:{costume,gender,breastSize:gender==='Female'?50:0}}).character;assert.equal(p.outfit,'Superhero');assert.equal(p.gender,gender);assert.notEqual(p.power,'None');assert.equal(p.costume,costume);call('configure_lego_character',{profile:{shirtColor:'#10bb99',cape:'None',face:'Freckles'}});assert.equal(b.read().characters.items[0].profile.shirtColor,'#10bb99','costume stays editable');}
// Powers share normal movement collision, including high speed and ceiling contact.
load();let v=call('control_lego_character',{power:'Flying',usePower:true,vertical:1,right:1,seconds:.5});assert(v.player.y>3&&v.powerStatus.flying);const y=v.player.y;v=call('control_lego_character',{seconds:.4});assert(Math.abs(v.player.y-y)<.001,'flight hovers');v=call('control_lego_character',{vertical:-1,seconds:.2});assert(v.player.y<y);call('control_lego_character',{usePower:true,seconds:1});assert(!b.read().player.flying&&b.read().player.grounded,'toggle flight lands');
load([{id:1,x:-4,z:-4,y:19,rows:8,cols:8,turn:0,kind:'plate',color:8},...tower(20,-4,-4,'support',6)]);v=call('control_lego_character',{power:'Flying',usePower:true,vertical:1,seconds:2});const top=Math.max(...R.core(b.debug().controller.state.rigContact,b.debug().controller.state).map(a=>a.max[1]));assert(top<=7.6+.02,'flight cannot pass through the roof');
load();v=call('control_lego_character',{power:'Super jumping',usePower:true,seconds:.45});assert(v.player.y>6,'super jump launches high');call('control_lego_character',{seconds:2});assert(b.read().player.grounded);call('control_lego_character',{jump:true,seconds:.3});assert(b.read().player.y>4,'ordinary Jump also uses super jumping');
load();v=call('control_lego_character',{power:'Super speed',usePower:true,right:1,run:true,seconds:.25});assert(v.player.x>5.6,'speed boost exceeds normal running speed');call('control_lego_character',{right:1,run:true,seconds:3});assert(b.debug().controller.contains(b.read().player.x,b.read().player.z),'boost remains within world');call('control_lego_character',{seconds:5});assert.equal(b.read().player.speedBoost,0,'boost expires');
load(tower(1,-1,-4,'wall',10));v=call('control_lego_character',{power:'Super speed',usePower:true,forward:1,run:true,seconds:2});assert(v.player.z> -1.6,'boost cannot tunnel through a wall');assert(!R.coreContacts(b.debug().controller.state.rigContact,b.debug().controller.state).length);
load(tower(1,-1,-4,'wall',10));v=call('control_lego_character',{power:'Climbing',usePower:true,forward:1,seconds:1});assert(v.player.y>3,'climbing ascends a contacted wall');assert(v.player.climbing);call('control_lego_character',{jump:true,seconds:.1});assert(!b.read().player.climbEnabled,'jump releases climb');
// Every destructive power records exact originals for rebuilding.
for(const power of ['Strength','Claws','Laser eyes','Energy constructs']){const extra=tower(1,-1,power==='Strength'||power==='Claws'?-4:-7,'target');load(extra);call('control_lego_character',{power,usePower:true,seconds:1});assert(b.read().broken.length,power+' destroys bricks');assert.equal(b.read().pieces.length,ground.length);assert.equal(b.read().broken[0].originals.length,extra.length);if(power==='Laser eyes')assert(b.debug().combatEffects.length>=0);call('control_lego_character',{forward:1,seconds:power==='Strength'||power==='Claws'?.1:.85});const before=b.read().player;call('control_lego_character',{rebuild:true,seconds:2});assert.equal(b.read().pieces.length,ground.length+extra.length,power+' rebuilds every original');assert(Math.hypot(b.read().player.x-before.x,b.read().player.z-before.z)<.0001,'no rebuild teleport');}
load([], [{id:1,profile:C.defaults,role:'Runner',state:{x:0,y:.4,z:-5,heading:0}}]);call('control_lego_character',{power:'Freezing breath',usePower:true,seconds:.3});const n=b.debug().npcs[0];assert(n.state.frozen>4.8&&n.state.frozen<=5);const frozen=[n.state.x,n.state.z];call('control_lego_character',{seconds:2});assert(Math.hypot(n.state.x-frozen[0],n.state.z-frozen[1])<.001,'frozen NPC stops walking');call('control_lego_character',{seconds:5});assert.equal(n.state.frozen,0,'NPC thaws');
load([], [{id:1,profile:C.defaults,role:'Runner',biome:'prairie',state:{x:0,y:.4,z:-6,heading:0}}]);call('control_lego_character',{power:'Read minds',usePower:true,seconds:.4});assert(b.debug().conversation?.mindReading);assert(b.elements['#bb-npc-speech'].textContent.includes('racecourse'));assert(!b.elements['#bb-conversation'].hidden,'mind reading dialog remains visible beyond ordinary chat range');b.fire('bb-talk-close');
load(tower(1,-1,-6,'lift'));call('control_lego_character',{power:'Telekinesis',usePower:true,seconds:.5});assert(b.debug().heroLift&&!b.debug().heroLift.thrown);assert.equal(b.read().broken.length,1);assert(b.debug().heroLift.position[1]>b.debug().heroLift.center[1]+1.8);call('control_lego_character',{usePower:true,seconds:1.8});assert.equal(b.debug().heroLift,null,'throw completes within the world');for(const d of b.debug().combatEffects)assert(d.position.every(Number.isFinite));call('control_lego_character',{forward:1,seconds:.5});call('control_lego_character',{rebuild:true,seconds:2});assert.equal(b.read().pieces.length,ground.length+4,'thrown creation rebuilds exactly');
load(tower(1,-1,-6,'lift'));call('control_lego_character',{power:'Telekinesis',usePower:true,seconds:.5});call('control_lego_character',{power:'None',seconds:.1});assert.equal(b.debug().heroLift,null,'changing powers releases lift');call('explore_lego_world',{playing:false});assert.equal(b.debug().heroPending,null);assert.equal(b.debug().heroConstruct,null);
load([...tower(1,-1,-5,'lift'),...tower(10,1,-8,'side-wall')]);call('control_lego_character',{power:'Telekinesis',usePower:true,seconds:.5});call('control_lego_character',{usePower:true,seconds:2});assert(b.read().broken.some(e=>e.originals.some(p=>p.group==='side-wall')),'the side of a thrown build collides even when its center misses');
load(tower(1,-1,-6,'lift'));call('control_lego_character',{power:'Telekinesis',usePower:true,seconds:.5});load();assert.equal(b.debug().heroLift,null,'loading another world cancels the old lift');
// Free flight reaches above the old ceiling, follows view pitch, and preserves 3D speed.
load();call('control_lego_character',{power:'Flying',usePower:true,vertical:1,run:true,seconds:4});assert(b.read().player.y>100,'flight rises higher than the former eighty-stud limit');let start={...b.read().player};call('control_lego_character',{forward:1,lookPitch:-.7,seconds:.3});assert(b.read().player.y>start.y+2&&b.read().player.z<start.z-2,'look up and move forward to fly diagonally upward');start={...b.read().player};call('control_lego_character',{right:-1,forward:-1,vertical:-1,lookPitch:0,seconds:.2});assert(b.read().player.x<start.x&&b.read().player.z>start.z&&b.read().player.y<start.y,'backward, sideward and descending input combine');let c=b.debug().controller;Object.assign(c.state,{y:319});call('control_lego_character',{vertical:1,run:true,seconds:.2});assert(b.read().player.y<=320&&b.read().player.y>=319,'flight retains a finite high ceiling');
// Horizontal travel smoothly becomes a prone pose, with connected trailing
// legs and a leading hand; vertical flight keeps the original upright pose.
load();call('control_lego_character',{power:'Flying',usePower:true,vertical:1,seconds:.8});assert.equal(b.read().player.flightCruise,0,'pure rise stays upright');call('control_lego_character',{forward:1,lookPitch:0,seconds:.1});assert(b.read().player.flightCruise>0&&b.read().player.flightCruise<.6,'cruise blends in instead of snapping');call('control_lego_character',{forward:1,seconds:.7});assert(b.read().player.flightCruise>.99,'travel settles into cruise');call('control_lego_character',{seconds:.8});assert(b.read().player.flightCruise<.01,'stopping returns smoothly to hover');
const flightProfile=C.validate({...C.defaults,power:'Flying',held:'None'});
for(const heading of [0,.8,Math.PI])for(const cruise of [0,.2,.5,.8,1])for(const tilt of [-.65,0,.65]){
 const state={x:4,y:8,z:-3,heading,grounded:false,flying:true,flightCruise:cruise,flightTilt:tilt,vy:0,airTime:2,phase:1,speed:16},pose=M.jointPose(state,false,flightProfile);
 for(const bone of Object.values(pose))assert(Array.from(bone).every(Number.isFinite),'finite flight transition');
 for(const [child,parent] of Object.entries(M.parents)){const anchor=M.transform(pose[parent],M.pivots[child].map((v,k)=>v-M.pivots[parent][k]));assert(anchor.every((v,k)=>Math.abs(v-pose[child][12+k])<.0001),'flight keeps '+child+' connected');}
 if(cruise===1&&tilt===0){const front=[Math.sin(heading),0,Math.cos(heading)],along=p=>p.reduce((v,x,k)=>v+x*front[k],0),hand=M.transform(pose.rightForearm,[.02,-.61,.06]),hips=Array.from(pose.hips.slice(12,15)),foot=Array.from(pose.rightFoot.slice(12,15));assert(pose.root[5]<.3,'cruise torso is nearly horizontal');assert(along(hand)>along(hips)+1.5,'leading hand extends along travel');assert(along(foot)<along(hips)-1,'legs trail behind');assert(pose.head[8]*front[0]+pose.head[10]*front[2]>.85,'head looks forward');}
}
load();call('control_lego_character',{power:'Super speed',usePower:true,right:1,run:true,seconds:.2});assert(b.read().player.x>9.2,'speedster runs at six times ordinary speed');assert(b.read().player.phase<5,'running cadence stays smooth at increased travel speed');
// Ice encloses intact scenery and neighbors for exactly five seconds.
const cold=tower(1,-1,-6,'frozen');load(cold);call('control_lego_character',{power:'Freezing breath',usePower:true,seconds:.3});assert.equal(b.read().broken.length,0,'freezing does not destroy creations');assert.equal(b.read().pieces.length,ground.length+cold.length);assert.equal(b.debug().frozenBricks.size,cold.length,'the whole connected creation receives ice');call('control_lego_character',{power:'Strength',seconds:4.8});assert(b.debug().frozenBricks.size,'switching powers does not cancel ice early');call('control_lego_character',{seconds:.2});assert.equal(b.debug().frozenBricks.size,0,'ice melts at five seconds');assert.equal(b.read().pieces.length,ground.length+cold.length,'thawing leaves every original intact');
load([], [{id:1,profile:C.defaults,role:'Runner',state:{x:0,y:.4,z:-5,heading:0}}]);call('control_lego_character',{power:'Freezing breath',usePower:true,seconds:.3});let neighbor=b.debug().npcs[0],phase=neighbor.state.phase;call('control_lego_character',{seconds:4.8});assert(neighbor.state.frozen>0&&neighbor.state.phase===phase,'encased NPC pose remains still');call('control_lego_character',{seconds:.2});assert.equal(neighbor.state.frozen,0,'NPC thaws after five seconds');
// Q claws uses the same punch pose, including hips and torso, even with an item equipped.
const clawProfile=C.validate({...C.defaults,power:'Claws',held:'None'}),plainProfile=C.defaults;
for(let i=0;i<30;i++){const state={x:0,y:.4,z:0,heading:.7,grounded:true,attack:.52*(1-i/30),heroAction:'Claws',heroTime:.52*(1-i/30),heroDuration:.52},claw=M.jointPose(state,false,clawProfile),punch=M.jointPose({...state,heroAction:null},false,plainProfile);for(const key of Object.keys(claw))assert(Array.from(claw[key]).every((v,k)=>Math.abs(v-punch[key][k])<.00001),'claw uses actual punch joint '+key);}
load(tower(1,-1,-4,'claw'));call('control_lego_character',{weapon:'Club',power:'Claws',usePower:true,seconds:.12});assert.equal(b.debug().controller.state.attackWeapon,'None');assert(b.debug().controller.state.attack>0);call('control_lego_character',{seconds:.3});assert(b.read().broken.length,'claw punch lands with a weapon stowed');
// A shuffled bag supplies all six designs, each with green geometry and its own impact.
load();const kinds=[];for(let i=0;i<12;i++){call('control_lego_character',{power:'Energy constructs',usePower:true,seconds:.1});const construct=b.debug().heroConstruct;assert(construct,'construct forms before contact');kinds.push(construct.kind);call('control_lego_character',{seconds:1.2});assert.equal(b.debug().heroConstruct,null,'construct fades after impact');}assert.equal(new Set(kinds.slice(0,6)).size,6,'first bag visits all six designs');assert.equal(new Set(kinds.slice(6)).size,6,'next bag also visits all designs');for(let i=1;i<kinds.length;i++)assert.notEqual(kinds[i],kinds[i-1],'no repeated neighboring constructs');
for(const kind of Object.keys(S.constructs)){load(tower(1,-1,-7,'construct'));b.debug().forceConstruct(kind);call('control_lego_character',{power:'Energy constructs',usePower:true,seconds:.1});const construct=b.debug().heroConstruct;assert.equal(construct.kind,kind);call('control_lego_character',{seconds:1.2});assert(b.read().broken.length,kind+' construct impacts scenery');call('control_lego_character',{forward:1,seconds:.85});call('control_lego_character',{rebuild:true,seconds:2});assert.equal(b.read().pieces.length,ground.length+4,kind+' preserves exact rebuilding');}
// Real hero poses keep elbows/knees connected and use finite geometry.
const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,createBuffer:()=>({}),createShader:()=>({}),createProgram:()=>({})},{get:(o,k)=>k in o?o[k]:(k.toUpperCase()===k?1:()=>{})}),renderer=M.create(gl,'void main(){}');
// Flight must retain a complete punch cycle rather than pinning the arms.
for(const cruise of [0,1])for(const heading of [0,1.2]){
 const hands=[];for(let i=0;i<=30;i++){const state={x:0,y:8,z:0,heading,grounded:false,flying:true,flightCruise:cruise,attack:.52*(1-i/30),attackWeapon:'None',airTime:2},pose=M.jointPose(state,false,flightProfile);hands.push(M.transform(pose.rightForearm,[.02,-.61,.06]));for(const [child,parent] of Object.entries(M.parents)){const anchor=M.transform(pose[parent],M.pivots[child].map((v,k)=>v-M.pivots[parent][k]));assert(anchor.every((v,k)=>Math.abs(v-pose[child][12+k])<.0001),'airborne punch connected '+child);}}
 assert(Math.max(...hands.map(p=>Math.hypot(...p.map((v,k)=>v-hands[0][k]))))>.4,'flying punch visibly winds up and extends');assert(Math.hypot(...hands[0].map((v,k)=>v-hands.at(-1)[k]))<.0001,'punch recovers to flight pose');
}
load([],null,flightProfile,{x:0,y:8,z:0,heading:Math.PI});call('control_lego_character',{power:'Flying',usePower:true,smash:true,seconds:.12});assert(b.read().player.attack>0&&b.read().player.flying,'attack starts without cancelling flight');call('control_lego_character',{seconds:.5});assert.equal(b.read().player.attack,0,'airborne punch completes');assert(b.read().player.flying);
// Hero cuts, body sliders and molded shape options change real meshes and save.
const female=C.validate({...C.defaults,gender:'Female',outfit:'Superhero',breastSize:70});
const shapes=[];for(const breastShape of C.choices.breastShape){const p=C.validate({...female,breastShape,buttSize:70});const rig=renderer.collisionParts(p);assert(rig.parts.every(g=>g.localBounds.min.concat(g.localBounds.max).every(Number.isFinite)));shapes.push(Buffer.from(renderer.appearanceAtlas(p,'torso').data).toString('base64'));}assert.equal(new Set(shapes).size,C.choices.breastShape.length,'all breast shapes visibly differ');
const cuts=[];for(const heroCut of C.choices.heroCut){const p=C.validate({...female,heroCut});cuts.push(['torso','leftArm','rightArm','leftLeg','dress'].map(slot=>Buffer.from(renderer.appearanceAtlas(p,slot).data).toString('base64')).join('|'));renderer.collisionParts(p);}assert.equal(new Set(cuts).size,C.choices.heroCut.length,'all uniform styles visibly differ');
const rear=size=>Math.min(...renderer.collisionParts(C.validate({...female,buttSize:size})).parts.filter(p=>p.slot==='rightLeg').map(p=>p.localBounds.min[2]));assert(rear(100)<rear(0)-.2,'butt slider changes rear molded geometry');
for(const name of ['Solar heroine','Emerald heroine','Cosmic heroine','Wild heroine']){const p=C.preset(name);assert.equal(p.gender,'Female');assert.notEqual(p.heroCut,'Full suit');call('configure_lego_character',{preset:name,profile:{buttSize:62,breastShape:'Teardrop',breastSize:54}});const saved=b.read().characters.items[0].profile;assert.equal(saved.buttSize,62);assert.equal(saved.breastShape,'Teardrop');}
const buttShapes=[];for(const buttShape of C.choices.buttShape){const p=C.validate({...female,buttShape,buttSize:80});buttShapes.push(Buffer.from(renderer.appearanceAtlas(p,'rightLeg').data).toString('base64'));}assert.equal(new Set(buttShapes).size,C.choices.buttShape.length,'all butt shapes visibly differ');
let previous=-Infinity;for(const breastSize of [0,10,20,40,60,80,100,110,120,130,140,150]){const p=C.validate({...female,breastSize}),extent=Math.max(...renderer.collisionParts(p).parts.filter(p=>p.slot==='torso').map(p=>p.localBounds.max[2]));assert(extent>previous,'each breast size increases molded depth: '+breastSize);previous=extent;}
const openings=[];for(const neckline of C.choices.neckline){const p=C.validate({...female,neckline,necklineDepth:80,necklineWidth:70});openings.push(Buffer.from(renderer.appearanceAtlas(p,'torso').data).toString('base64'));}assert.equal(new Set(openings).size,C.choices.neckline.length,'neckline styles have different actual cutouts');
for(const key of ['necklineDepth','necklineWidth']){const views=[];for(const value of [0,50,100]){const p=C.validate({...female,neckline:'V-neck',[key]:value});views.push(Buffer.from(renderer.appearanceAtlas(p,'torso').data).toString('base64'));}assert.equal(new Set(views).size,3,key+' updates opening geometry');}
for(const name of ['Storm heroine','Night huntress','Star heroine','Crimson heroine','Golden warrior','Speed heroine']){const p=C.preset(name);assert.equal(p.gender,'Female');assert.notEqual(p.neckline,'Closed');renderer.collisionParts(p);call('configure_lego_character',{preset:name,profile:{breastSize:150,buttShape:'Pear',necklineDepth:75,necklineWidth:62}});const saved=b.read().characters.items[0].profile;assert.equal(saved.breastSize,150);assert.equal(saved.buttShape,'Pear');assert.equal(saved.necklineDepth,75);assert.equal(saved.necklineWidth,62);}
// New molded profiles scale continuously from tiny to large.
for(const breastShape of ['Perky','Pointy']){let previous=-Infinity;for(const breastSize of [5,15,45,90,150]){const p=C.validate({...female,breastShape,breastSize}),rig=renderer.collisionParts(p),depth=Math.max(...rig.parts.filter(p=>p.slot==='torso').map(p=>p.localBounds.max[2]));assert(depth>previous,breastShape+' grows with size');previous=depth;assert(rig.parts.every(g=>g.localBounds.min.concat(g.localBounds.max).every(Number.isFinite)));}}
const fashions=[];for(const lingerie of C.choices.lingerie){const p=C.validate({...female,outfit:'Lingerie',lingerie,neckline:'Closed',buttSize:50,breastShape:'Perky'});fashions.push(['torso','rightLeg'].map(slot=>Buffer.from(renderer.appearanceAtlas(p,slot).data).toString('base64')).join('|'));renderer.collisionParts(p);}assert.equal(new Set(fashions).size,C.choices.lingerie.length,'all lingerie styles visibly differ');
// Printed chest artwork uses all shape/size choices without protruding geometry.
assert.equal(C.validate({gender:'Female',breastSize:70}).breastMode,'Sculpted','old profiles retain the sculpted default');
const printed=C.validate({...female,breastMode:'Printed',outfit:'Separates',shirt:'T-shirt',pattern:'Plain'}),printedShapes=[];
const chestDepth=p=>Math.max(...renderer.collisionParts(p).parts.filter(g=>g.slot==='torso').map(g=>g.localBounds.max[2]));
const flatDepth=chestDepth({...printed,breastSize:0});
for(const breastShape of C.choices.breastShape){const p=C.validate({...printed,breastShape});printedShapes.push(Buffer.from(renderer.appearanceAtlas(p,'torso').data).toString('base64'));assert(Math.abs(chestDepth(p)-flatDepth)<1e-5,'printed '+breastShape+' stays flat');}
assert.equal(new Set(printedShapes).size,C.choices.breastShape.length,'every printed shape visibly differs');
const comicShapes=[];for(const breastShape of C.choices.breastShape){const p=C.validate({...printed,breastMode:'Comic',breastShape}),atlas=renderer.appearanceAtlas(p,'torso');comicShapes.push(Buffer.from(atlas.data).toString('base64'));assert(Math.abs(chestDepth(p)-flatDepth)<1e-5,'comic '+breastShape+' stays flat');let ink=0;for(let i=0;i<atlas.data.length;i+=4)if(atlas.data[i]===32&&atlas.data[i+1]===32&&atlas.data[i+2]===42)ink++;assert(ink>10,breastShape+' has visible comic contour ink');assert.notEqual(comicShapes.at(-1),printedShapes[C.choices.breastShape.indexOf(breastShape)],'comic differs from shaded 2D');}assert.equal(new Set(comicShapes).size,C.choices.breastShape.length,'all comic shapes visibly differ');
const comicSizes=[];for(const breastSize of [0,5,15,45,90,150]){const p=C.validate({...printed,breastMode:'Comic',breastSize});comicSizes.push(Buffer.from(renderer.appearanceAtlas(p,'torso').data).toString('base64'));assert(Math.abs(chestDepth(p)-flatDepth)<1e-5,'comic sizes retain flat contact geometry');}assert.equal(new Set(comicSizes).size,6,'comic sizes change the artwork');
for(const w of [{armLengths:[1.35,1.25]},{style:'fire'},{twoHand:true}]){const comicArm=M.weaponArmLengths(w,C.validate({...printed,breastMode:'Comic'})),printArm=M.weaponArmLengths(w,printed);assert.deepEqual(comicArm,printArm,'comic arms use flat chest clearance');if(w.armLengths||w.style==='fire')assert(M.weaponArmLengths(w,female)[0]>comicArm[0],'only sculpted mode adds physical chest clearance');}
const printedSizes=[];for(const breastSize of [0,5,15,45,90,150]){const p=C.validate({...printed,breastSize});printedSizes.push(Buffer.from(renderer.appearanceAtlas(p,'torso').data).toString('base64'));assert(Math.abs(chestDepth(p)-flatDepth)<1e-5,'printed size stays flat');}assert.equal(new Set(printedSizes).size,6,'printed sizes change the drawing');
const underwearViews=[];for(const underwear of C.choices.underwear){const p=C.validate({...female,outfit:'Underwear',underwear,neckline:'Closed',buttSize:50});underwearViews.push(['torso','rightLeg'].map(slot=>Buffer.from(renderer.appearanceAtlas(p,slot).data).toString('base64')).join('|'));}assert.equal(new Set(underwearViews).size,C.choices.underwear.length,'all underwear styles visibly differ');
for(const name of ['High waist underwear','Bralette and boyshorts','Balcony underwear','Triangle underwear','Sport micro shorts set','Longline underwear','Lace bodysuit','Corset and briefs','Longline lace lingerie','Halter lingerie','Ribbon lingerie','High waist lingerie']){call('configure_lego_character',{preset:name,profile:{breastMode:'Printed',breastShape:'Pointy',breastSize:90}});const p=b.read().characters.items[0].profile;assert.equal(p.gender,'Female');assert.equal(p.breastMode,'Printed');assert.equal(p.breastSize,90);assert(['Underwear','Lingerie'].includes(p.outfit));}
// Rear hems expose skin, and a continuous band sits outside actual rear meshes.
const backDepth=(parts,x,y,predicate)=>{let depth=Infinity;for(const g of parts){if(!predicate(g))continue;const v=g.surface.vertices,pivot=M.pivots[g.joint];for(let i=0;i<v.length;i+=9){const a=[0,1,2].map(k=>v[i+k]+pivot[k]),b=[0,1,2].map(k=>v[i+3+k]+pivot[k]),c=[0,1,2].map(k=>v[i+6+k]+pivot[k]),den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-8)continue;const u=((b[1]-c[1])*(x-c[0])+(c[0]-b[0])*(y-c[1]))/den,w=((c[1]-a[1])*(x-c[0])+(a[0]-c[0])*(y-c[1]))/den,t=1-u-w;if(Math.min(u,w,t)>=-1e-6)depth=Math.min(depth,a[2]*u+b[2]*w+c[2]*t);}}return depth;};
for(const buttShape of C.choices.buttShape)for(const buttSize of [0,35,100]){
 const p=C.validate({...female,outfit:'Separates',pants:'Thong',buttShape,buttSize}),parts=renderer.inspect(p);
 for(const x of [-.65,-.50,-.30,0,.30,.50,.65]){const band=backDepth(parts,x,1.89,g=>g.joint==='hips'&&g.locked&&g.surface.color===p.pantsColor),skin=backDepth(parts,x,1.89,g=>g.surface.color===p.skinColor);assert(Number.isFinite(band),'waistband has no back gap '+buttShape+' '+buttSize+' '+x);assert(band<skin-.012,'waistband stays outside skin '+buttShape+' '+buttSize+' '+x);}
 if(buttSize>0){const micro=renderer.inspect(C.validate({...p,pants:'Micro shorts'})),briefs=renderer.inspect(C.validate({...p,pants:'Briefs'}));for(const parts of [micro,briefs]){const skin=backDepth(parts,.39,1.45,g=>g.surface.color===p.skinColor),cloth=backDepth(parts,.39,1.45,g=>g.surface.color===p.pantsColor);assert(Number.isFinite(skin)&&skin<cloth,'lower rear is skin below the garment hem');}}
}
const pantsViews=[];for(const pants of ['Shorts','Micro shorts','Thong']){const p=C.validate({...female,outfit:'Separates',pants});pantsViews.push(['torso','rightLeg'].map(slot=>Buffer.from(renderer.appearanceAtlas(p,slot).data).toString('base64')).join('|'));}assert.equal(new Set(pantsViews).size,3,'micro shorts and thong differ from regular shorts');
for(const name of ['Micro shorts outfit','Lace lingerie','Satin lingerie','Thong lingerie','Bustier set','Bodysuit lingerie','Camisole and thong']){call('configure_lego_character',{preset:name,profile:{breastShape:'Pointy',breastSize:15}});const saved=b.read().characters.items[0].profile;assert.equal(saved.breastShape,'Pointy');assert.equal(saved.breastSize,15);if(name!=='Micro shorts outfit')assert.equal(saved.outfit,'Lingerie');else assert.equal(saved.pants,'Micro shorts');}
assert.throws(()=>C.validate({...female,breastSize:151}));assert.throws(()=>C.validate({...female,necklineWidth:101}));
assert.throws(()=>C.validate({...female,buttSize:101}));assert.equal(C.validate({gender:'Female'}).buttSize,0);
for(const power of Object.keys(S.powers).filter(p=>p!=='None')){const p=C.validate({...C.defaults,power,held:'None'}),c=new P.Controller(ground);renderer.bindCollision(p,c);for(let i=0;i<30;i++){Object.assign(c.state,{heroAction:['Strength','Claws','Energy constructs','Laser eyes','Freezing breath'].includes(power)?power:null,heroTime:1-i/30,heroDuration:1,flying:power==='Flying',climbing:power==='Climbing',phase:i*.1,grounded:power==='Strength',y:power==='Strength'?.4:5});c.state.rigContact.clock=i/60;const pose=M.jointPose(c.state,false,p);for(const m of Object.values(pose))assert(Array.from(m).every(Number.isFinite));for(const [child,parent] of Object.entries(M.parents)){const anchor=M.transform(pose[parent],M.pivots[child].map((v,k)=>v-M.pivots[parent][k]));assert(anchor.every((v,k)=>Math.abs(v-pose[child][12+k])<.0001),power+' connected '+child);}}}
assert.throws(()=>call('configure_lego_character',{profile:{power:'Not a power'}}));console.log('PASS: 22 male/female costume combinations, editable assets, eleven powers, shared high-speed/flight/climbing collisions and boundaries, super jump, NPC freeze/thaw and mind dialog, telekinetic lift/throw/cancellation, exact repairs without teleporting, and connected finite hero rigs.');
