const CharacterArt=(()=>{
'use strict';
const views=['Front','Back','Left','Right','Top','Bottom'],cell=128;
const regions={head:[.27,.03,.46,.25],hair:[.24,.0,.52,.14],torso:[.20,.28,.60,.30],leftLeg:[.22,.58,.27,.33],rightLeg:[.51,.58,.27,.33],leftFoot:[.18,.90,.30,.10],rightFoot:[.52,.90,.30,.10],hat:[.22,0,.56,.15],back:[.12,.29,.76,.31],held:[.74,.30,.23,.35]};
function sample(pixels,width,height,rect){const bins=new Map();const x0=Math.max(0,Math.floor(rect.x)),y0=Math.max(0,Math.floor(rect.y)),x1=Math.min(width,Math.ceil(rect.x+rect.w)),y1=Math.min(height,Math.ceil(rect.y+rect.h));for(let y=y0;y<y1;y+=Math.max(1,Math.floor((y1-y0)/28)))for(let x=x0;x<x1;x+=Math.max(1,Math.floor((x1-x0)/28))){const i=(y*width+x)*4;if(pixels[i+3]<80)continue;const r=pixels[i],g=pixels[i+1],b=pixels[i+2];if(Math.min(r,g,b)>235)continue;const key=[r,g,b].map(v=>Math.floor(v/32)).join(',');const bin=bins.get(key)||{n:0,r:0,g:0,b:0};bin.n++;bin.r+=r;bin.g+=g;bin.b+=b;bins.set(key,bin);}if(!bins.size)return '#d0c5ae';const b=[...bins.values()].sort((a,b)=>b.n-a.n)[0];return '#'+[b.r,b.g,b.b].map(v=>Math.round(v/b.n).toString(16).padStart(2,'0')).join('');}
function analyze(pixels,width,height,crop){const rects={};for(const [part,[x,y,w,h]] of Object.entries(regions))rects[part]={x:crop.x+x*crop.w,y:crop.y+y*crop.h,w:w*crop.w,h:h*crop.h};const palette={skinColor:sample(pixels,width,height,{x:crop.x+crop.w*.4,y:crop.y+crop.h*.12,w:crop.w*.2,h:crop.h*.10}),hairColor:sample(pixels,width,height,rects.hair),shirtColor:sample(pixels,width,height,rects.torso),pantsColor:sample(pixels,width,height,rects.leftLeg),shoeColor:sample(pixels,width,height,rects.leftFoot),hatColor:sample(pixels,width,height,rects.hat),accessoryColor:sample(pixels,width,height,rects.back)};palette.dressColor=palette.shirtColor;return {rects,palette};}
function stylize(pixels,steps=7){const result=new Uint8ClampedArray(pixels);const stride=255/(steps-1);for(let i=0;i<result.length;i+=4){for(let j=0;j<3;j++)result[i+j]=Math.round(Math.round(result[i+j]/stride)*stride);result[i+3]=pixels[i+3];}return result;}
function rect(crop,width,height){if(!crop||![crop.x,crop.y,crop.w,crop.h].every(Number.isFinite)||crop.w<3||crop.h<3)throw Error('Select a larger area in the photo.');const x=Math.max(0,Math.min(width-3,crop.x)),y=Math.max(0,Math.min(height-3,crop.y));return {x,y,w:Math.max(3,Math.min(width-x,crop.w)),h:Math.max(3,Math.min(height-y,crop.h))};}
return {views,cell,regions,sample,analyze,stylize,rect};
})();
