// Character studio and playable world share the same editable brick scene.
const characterRenderer=CharacterModel.create(gl,fragment,()=>{dirty=true;}),characterFields=new Map();
let controller=null,physicsRevision=-1,previewCameraBackup=null,heldKeys=new Set(),touchMove=new Set(),runHeld=new Set(),jumpHeld=new Set(),runToggle=false,jumpRequested=false,rebuildHeld=false,gameMessageUntil=0,smashCooldown=0,saveClock=0,lastGameTarget='',rebuildEntry=null;
let studioHeightScale=1;
let debris=[],debrisClock=0,pendingSmash=null,pendingSpell=null;
let rebuildGuide=null,rebuildGuideMeshes=null,rebuildGuideAttempt=null,rebuildArrow=null,rebuildSafety=null;
function rebuildTarget(){
 const entry=rebuildEntry||broken.find(b=>b.id===rebuildGuide?.entryId);
 if(entry&&controller){const s=controller.state,b=damagedBounds(entry),near=Math.hypot(Math.max(b.x0-s.x,0,s.x-b.x1),Math.max(b.z0-s.z,0,s.z-b.z1))<=3.4&&b.y0<s.y+4.5;
  if(near&&(rebuildEntry||Math.hypot(s.x-rebuildGuide.x,s.z-rebuildGuide.z)<.9))return entry;
 }return nearestBroken();
}
function rebuildDirection(spot){
 const entry=broken.find(b=>b.id===spot.entryId);if(!entry)return null;
 let target=null;
 for(const p of entry.originals){const b=GamePhysics.bounds(p);let x=Math.max(b.x0,Math.min(spot.x,b.x1)),z=Math.max(b.z0,Math.min(spot.z,b.z1));
  if(Math.hypot(x-spot.x,z-spot.z)<.01){x=(b.x0+b.x1)/2;z=(b.z0+b.z1)/2;if(Math.hypot(x-spot.x,z-spot.z)<.01)x=b.x1;}
  const distance=Math.hypot(x-spot.x,z-spot.z);if(!target||distance<target.distance)target={x,z,dx:(x-spot.x)/distance,dz:(z-spot.z)/distance,distance,entryId:entry.id};
 }return target;
}
function safeToRebuild(entry,s){
 const key=[renderRevision,entry.id,s.x,s.y,s.z].join('|');
 if(rebuildSafety?.key!==key)rebuildSafety={key,safe:!entry.originals.some(p=>GamePhysics.overlapsPlayer(p,s))&&!GamePhysics.rebuildTraps(controller,entry.originals,s.x,s.z,s.y)};
 return rebuildSafety.safe;
}
function rebuildGuidance(){
 if(!playing||!controller||conversation){rebuildGuide=null;rebuildGuideAttempt=null;return null;}
 const entry=rebuildTarget();if(!entry){rebuildGuide=null;rebuildGuideAttempt=null;return null;}
 const clearOfNeighbors=spot=>npcs.every(n=>Math.hypot(n.state.x-spot.x,n.state.z-spot.z)>1.8);
 if(rebuildGuide?.entryId===entry.id&&rebuildGuide.revision===renderRevision&&Math.abs(rebuildGuide.y-controller.state.y)<=.45)return rebuildGuide;
 const s=controller.state,a=rebuildGuideAttempt;if(!rebuildGuide&&a?.entryId===entry.id&&a.revision===renderRevision&&clock-a.time<.5&&Math.hypot(s.x-a.x,s.y-a.y,s.z-a.z)<.5)return null;
 const spot=GamePhysics.findRebuildSpot(controller,entry.originals,clearOfNeighbors);
 rebuildGuideAttempt={entryId:entry.id,revision:renderRevision,time:clock,x:s.x,y:s.y,z:s.z};
 rebuildGuide=spot?{...spot,entryId:entry.id,revision:renderRevision}:null;return rebuildGuide;
}
function drawRebuildGuide(){
 const spot=rebuildGuidance();if(!spot)return;
 if(!rebuildGuideMeshes){rebuildGuideMeshes=[];for(const [inner,outer,opacity] of [[.72,.91,.06],[.65,.81,.13],[.62,.72,.75],[0,.62,.06]]){
  positions=[];normals=[];for(let i=0;i<64;i++){const a=i*Math.PI/32,b=(i+1)*Math.PI/32,point=(r,t)=>[r*Math.cos(t),0,r*Math.sin(t)],n=[0,1,0];tri(point(inner,a),point(outer,a),point(outer,b),n,n,n);tri(point(inner,a),point(outer,b),point(inner,b),n,n,n);}
  rebuildGuideMeshes.push({mesh:upload(),opacity});
 }}
 const s=controller.state,ready=s.grounded&&Math.hypot(s.x-spot.x,s.z-spot.z)<.75,pulse=reducedMotion?1:.86+.14*Math.sin(clock*4),color=ready?[.30,1,.43]:[.15,.78,1];
 gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.depthMask(false);gl.uniform1f(sceneUniforms.explore,0);
 for(const band of rebuildGuideMeshes)drawMesh(band.mesh,[spot.x,spot.surface+.025,spot.z],color,band.opacity*pulse,false,true);
 const direction=rebuildDirection(spot);
 if(direction){const key=[spot.entryId,spot.x,spot.z,direction.x,direction.z].join('|');
  if(rebuildArrow?.key!==key){if(rebuildArrow){gl.deleteBuffer(rebuildArrow.mesh.p);gl.deleteBuffer(rebuildArrow.mesh.n);}positions=[];normals=[];
   const tip=Math.min(3.2,direction.distance-.08),head=Math.min(.55,tip*.45),tail=.20,neck=tip-head,n=[0,1,0],p=(t,w)=>[direction.dx*t-direction.dz*w,0,direction.dz*t+direction.dx*w];
   tri(p(tail,-.12),p(neck,-.12),p(neck,.12),n,n,n);tri(p(tail,-.12),p(neck,.12),p(tail,.12),n,n,n);tri(p(neck,-.37),p(tip,0),p(neck,.37),n,n,n);
   rebuildArrow={key,mesh:upload()};
  }
  // Keep the directional guide readable over studs, loose bricks, and the player.
  gl.disable(gl.DEPTH_TEST);drawMesh(rebuildArrow.mesh,[spot.x,spot.surface+.045,spot.z],color,.8*pulse,false,true);gl.enable(gl.DEPTH_TEST);
 }
 gl.uniform1f(sceneUniforms.explore,1);gl.depthMask(true);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.BLEND);
}
const fieldGroups={appearance:['gender','height','breastMode','breastSize','breastShape','nippleStyle','nippleSize','nippleColor','buttSize','buttShape','head','skinColor','hair','hairColor','face','eyes','eyeColor','expression','facialHair','glasses','glassesColor'],clothing:['costume','power','outfit','heroCut','neckline','necklineDepth','necklineWidth','shirt','shirtColor','pants','pantsColor','dress','dressColor','swimwear','underwear','lingerie','pattern','accentColor','shoes','shoeColor','gloves','gloveColor'],accessory:['hat','hatColor','back','cape','scarf','neck','ears','wrist','belt','held','spell','accessoryColor']};
const fieldLabels={costume:'Hero costume',power:'Superpower',gender:'Character type',height:'Character height',nippleStyle:'Nipple style · bare torso',nippleSize:'Nipple size · 0–100',nippleColor:'Nipple color',breastMode:'Breast style · sculpted, printed or comic',breastSize:'Breast size · 0–150',breastShape:'Breast shape',buttSize:'Butt size · 0 = classic hips',buttShape:'Butt shape',neckline:'Cleavage / neckline style',necklineDepth:'Cleavage depth',necklineWidth:'Cleavage width',heroCut:'Hero uniform style',head:'Head shape',hair:'Hair style',face:'Face details',eyes:'Eye shape',expression:'Expression',facialHair:'Facial hair',outfit:'Outfit type',shirt:'Shirt style',pants:'Pants / shorts / thong',dress:'Dress style',swimwear:'Swim style',lingerie:'Lingerie style',underwear:'Underwear style',back:'Back gear',neck:'Neck jewelry',ears:'Ears / headphones',wrist:'Wrist accessories',held:'Held item',spell:'Magic spell',accentColor:'Pattern / trim color',accessoryColor:'Accessory color'};
function activeProfile(){return characters.find(c=>c.id===activeCharacterId)?.profile||characters[0].profile;}
function activeCharacter(){return characters.find(c=>c.id===activeCharacterId)||characters[0];}
for(const [group,fields] of Object.entries(fieldGroups))for(const key of fields){const label=document.createElement('label'),input=document.createElement(CharacterCatalog.choices[key]?'select':'input');input.id='bb-character-'+key;label.htmlFor=input.id;label.textContent=fieldLabels[key]||key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());if(CharacterCatalog.choices[key])for(const text of CharacterCatalog.choices[key]){const option=document.createElement('option');option.value=text;option.textContent=text;input.appendChild(option);}else if(Object.hasOwn(CharacterCatalog.rangeFields,key)){input.type='range';input.min=0;input.max=CharacterCatalog.rangeFields[key].max;input.step=1;input.value=CharacterCatalog.defaults[key];}else input.type='color';label.appendChild(input);q('#bb-'+group+'-fields').appendChild(label);characterFields.set(key,{input,label});input.addEventListener(['color','range'].includes(input.type)?'input':'change',()=>{const profile=CharacterCatalog.validate(key==='costume'?SuperPowers.dress(activeProfile(),input.value):{...activeProfile(),[key]:Object.hasOwn(CharacterCatalog.rangeFields,key)?Number(input.value):input.value});if(!input._undoSaved){remember();input._undoSaved=['color','range'].includes(input.type);}activeCharacter().profile=profile;q('#bb-character-preset').value='';syncCharacter();persist();dirty=true;});if(['color','range'].includes(input.type))input.addEventListener('change',()=>{input._undoSaved=false;});}
for(const name of Object.keys(CharacterCatalog.presets)){const option=document.createElement('option');option.value=option.textContent=name;q('#bb-character-preset').appendChild(option);}
function syncCharacter(){syncWeapon();syncHero();const p=activeProfile();if(characterPreview){const scale=CharacterCatalog.heightScale(p);target[1]*=scale/studioHeightScale;studioHeightScale=scale;}for(const [key,{input,label}] of characterFields){input.value=p[key];label.hidden=['nippleSize','nippleColor'].includes(key)&&p.nippleStyle==='None'||['neckline','necklineDepth','necklineWidth'].includes(key)&&p.gender!=='Female'||['necklineDepth','necklineWidth'].includes(key)&&p.neckline==='Closed'||key==='heroCut'&&p.outfit!=='Superhero'||key==='spell'&&p.held!=='Wand'||['breastMode','breastSize','breastShape'].includes(key)&&p.gender!=='Female'||key==='shirt'&&p.outfit!=='Separates'||key==='pants'&&p.outfit!=='Separates'||key==='dress'&&p.outfit!=='Dress'||key==='dressColor'&&p.outfit!=='Dress'||key==='swimwear'&&!['Swimsuit','Bikini'].includes(p.outfit)||key==='underwear'&&p.outfit!=='Underwear'||key==='lingerie'&&p.outfit!=='Lingerie'||key==='shirtColor'&&p.outfit==='Dress'||key==='pantsColor'&&p.outfit==='Dress'||key==='hatColor'&&p.hat==='None'||key==='glassesColor'&&p.glasses==='None'||key==='gloveColor'&&p.gloves==='None';if(Object.hasOwn(CharacterCatalog.rangeFields,key))input.setAttribute('aria-valuetext',p[key]+' of '+CharacterCatalog.rangeFields[key].max);}q('#bb-character-name').value=p.name;q('#bb-preview-name').textContent=p.name;q('#bb-player-name').textContent=p.name;const roster=q('#bb-roster');roster.replaceChildren();for(const c of characters){const option=document.createElement('option');option.value=c.id;option.textContent=c.profile.name;roster.appendChild(option);}roster.value=activeCharacterId;refreshGamePickers();syncStudioAnimation();q('#bb-undo').disabled=!undoStack.length;q('#bb-redo').disabled=!redoStack.length;dirty=true;}
function newCharacter(duplicate=false){if(characters.length>=24){q('#bb-character-message').textContent='Your collection holds 24 characters. Edit any existing character.';return;}remember();const id=Math.max(0,...characters.map(c=>c.id))+1,profile=duplicate?{...activeProfile(),name:activeProfile().name.slice(0,26)+' copy'}:{...CharacterCatalog.defaults,name:'Builder '+id};characters.push({id,profile});activeCharacterId=id;syncCharacter();persist();}
let nameUndoSaved=false;q('#bb-character-name').addEventListener('blur',()=>{nameUndoSaved=false;});q('#bb-character-name').addEventListener('input',e=>{if(!nameUndoSaved){remember();nameUndoSaved=true;}activeCharacter().profile=CharacterCatalog.validate({...activeProfile(),name:e.target.value});q('#bb-preview-name').textContent=activeProfile().name;q('#bb-player-name').textContent=activeProfile().name;const option=[...q('#bb-roster').children].find(o=>Number(o.value)===activeCharacterId);if(option)option.textContent=activeProfile().name;persist();});
q('#bb-roster').addEventListener('change',e=>{activeCharacterId=Number(e.target.value);syncCharacter();persist();});q('#bb-character-new').addEventListener('click',()=>newCharacter());q('#bb-character-copy').addEventListener('click',()=>newCharacter(true));
q('#bb-character-preset').addEventListener('change',e=>{if(!e.target.value)return;remember();activeCharacter().profile=CharacterCatalog.preset(e.target.value);syncCharacter();persist();});
q('#bb-character-random').addEventListener('click',()=>{remember();const names=Object.keys(CharacterCatalog.presets),p=CharacterCatalog.preset(names[Math.floor(Math.random()*names.length)]);for(const k of ['gender','hair','expression','face','eyes'])p[k]=CharacterCatalog.choices[k][Math.floor(Math.random()*CharacterCatalog.choices[k].length)];p.name='Builder '+activeCharacterId;activeCharacter().profile=p;syncCharacter();q('#bb-character-preset').value='';persist();});
for(const details of root.querySelectorAll('.character-group'))details.addEventListener('toggle',()=>{if(details.open)for(const other of root.querySelectorAll('.character-group'))if(other!==details)other.open=false;});
function clearInput(){resetHero();pendingSpell=null;if(typeof fireHeld!=='undefined')fireHeld.clear();heldKeys.clear();touchMove.clear();runHeld.clear();jumpHeld.clear();jumpRequested=false;rebuildHeld=false;runToggle=false;q('#bb-run').setAttribute('aria-pressed','false');if(controller)controller.state.speed=0;cancelRebuild();}
function ensurePhysics(){const created=!controller,profile=activeProfile(),previousScale=controller?GamePhysics.scaleOf(controller.state):null;if(created)controller=new GamePhysics.Controller(pieces,world);characterRenderer.bindCollision(profile,controller);if(created&&savedPlayer&&validPlayer(savedPlayer))Object.assign(controller.state,savedPlayer,{attack:0,building:false,buildBlend:0,buildTime:0,landing:0,airTime:0,jumpBuffer:0,coyote:0});if(physicsRevision!==renderRevision){controller.replace(pieces,world);physicsRevision=renderRevision;controller.repairPosition();}if((created||previousScale!==CharacterCatalog.heightScale(profile))&&controller.sceneryContacts(controller.state.x,controller.state.y,controller.state.z).length)controller.spawn();return controller;}
function validPlayer(s){return s&&['x','y','z','heading'].every(k=>typeof s[k]==='number'&&Number.isFinite(s[k]))&&Math.abs(s.x)<=300&&Math.abs(s.z)<=300&&s.y>=-15&&s.y<=330;}
function resetAdventure(){resetHero(true);shots=[];combatEffects=[];weaponAmmo.clear();weaponOwner='';pendingSmash=null;pendingSpell=null;resetNPCs();playing=false;characterPreview=false;clearInput();controller=null;savedPlayer=null;physicsRevision=-1;broken=[];debris=[];rebuildEntry=null;updateGameVisibility();}
function updateGameVisibility(){root.dataset.mode=playing?'play':characterPreview?'preview':'build';q('#bb-build-tools').hidden=playing||characterPreview;q('#bb-preview-tools').hidden=!characterPreview;q('#bb-play-hud').hidden=!playing;q('#bb-weapon-bar').hidden=!playing;q('#bb-hero-bar').hidden=!playing;q('#bb-game-info').hidden=!playing;q('#bb-touch-controls').hidden=!playing;q('#bb-quick-play').textContent=playing?'Workshop':'Explore';syncGameUI();}
function leavePreview(){if(characterPreview&&previewCameraBackup){({yaw,pitch,target,baseDistance,zoom}=previewCameraBackup);q('#bb-zoom').value=zoom;previewCameraBackup=null;}characterPreview=false;}
function showCharacterStudio(){characterRenderer.setLivePaint(null);if(playing)stopPlaying(false);if(!characterPreview){previewCameraBackup={yaw,pitch,target:[...target],baseDistance,zoom};characterPreview=true;yaw=.13;pitch=.07;studioHeightScale=CharacterCatalog.heightScale(activeProfile());target=[0,2.52*studioHeightScale,0];baseDistance=10.7;zoom=55;}currentPanel='characters';q('#bb-world-panel').hidden=true;q('#bb-bricks-panel').hidden=true;q('#bb-art-panel').hidden=true;q('#bb-photo-panel').hidden=true;q('#bb-character-panel').hidden=false;for(const [id,on] of [['world',false],['bricks',false],['character',true]])q('#bb-'+id+'-tab').setAttribute('aria-pressed',String(on));selected=null;moving=null;tool='orbit';ghostVisible=false;stopTour();syncCharacter();updateGameVisibility();status('Drag to turn your character · Every change saves automatically.');dirty=true;}
function startPlaying(){leavePreview();ensurePhysics();ensureNPCs();playing=true;resetMapTouch();currentPanel='characters';clearInput();selected=null;moving=null;tool='orbit';ghostVisible=false;stopTour();yaw=controller.state.heading+Math.PI;pitch=.28;zoom=55;baseDistance=11.5;target=[controller.state.x,controller.state.y+2.1*CharacterCatalog.heightScale(activeProfile()),controller.state.z];syncCharacter();updateGameVisibility();gameMessage('Your adventure starts here. F attacks · R reloads · Hold E rebuilds · H opens the field guide.',4);persist();if(root.dataset.mobile==='true')root.scrollIntoView?.({block:'start',behavior:'instant'});canvas.focus({preventScroll:true});dirty=true;return {...controller.state};}
function stopPlaying(fitWorld=true){resetHero(true);shots=[];combatEffects=[];if(controller)Object.assign(controller.state,{reload:0,weaponRecoil:0,recoilVelocity:0});pendingSmash=null;pendingSpell=null;if(controller)controller.state.attack=0;closeConversation();if(controller)savedPlayer={...controller.state};playing=false;clearInput();rebuildEntry=null;updateGameVisibility();if(fitWorld)fit();persist();dirty=true;}
q('#bb-explore').addEventListener('click',startPlaying);q('#bb-quick-play').addEventListener('click',()=>playing?stopPlaying():startPlaying());q('#bb-character-tab').addEventListener('click',showCharacterStudio);q('#bb-edit-character').addEventListener('click',showCharacterStudio);q('#bb-exit-play').addEventListener('click',()=>stopPlaying());q('#bb-respawn').addEventListener('click',()=>{cancelRebuild();resetHero();shots=[];combatEffects=[];ensurePhysics().spawn();controller.state.reload=0;pendingSmash=null;pendingSpell=null;savedPlayer={...controller.state};dirty=true;gameMessage('Back on solid ground.',2);persist();});
q('#bb-front').addEventListener('click',()=>{yaw=0;pitch=.06;dirty=true;});q('#bb-back').addEventListener('click',()=>{yaw=Math.PI;pitch=.06;dirty=true;});
function gameMessage(text,seconds=2){q('#bb-game-message').textContent=text;gameMessageUntil=clock+seconds;}
function damagedBounds(entry){let b={x0:Infinity,x1:-Infinity,y0:Infinity,y1:-Infinity,z0:Infinity,z1:-Infinity};for(const p of entry.originals){const c=GamePhysics.bounds(p);for(const key of ['x0','y0','z0'])b[key]=Math.min(b[key],c[key]);for(const key of ['x1','y1','z1'])b[key]=Math.max(b[key],c[key]);}return b;}
function nearestBroken(){if(!controller)return null;const s=controller.state;let best=null,dist=Infinity;for(const entry of broken){const b=damagedBounds(entry),d=Math.hypot(Math.max(b.x0-s.x,0,s.x-b.x1),Math.max(b.z0-s.z,0,s.z-b.z1));if(d<=3.4&&b.y0<s.y+4.5&&d<dist){dist=d;best=entry;}}return best;}
function makeDebris(entry,impact=null){const ps=entry.originals,count=Math.min(36,Math.max(12,ps.length*3));for(let i=0;i<count;i++){const p=ps[i%ps.length],b=GamePhysics.bounds(p),x=b.x0+(b.x1-b.x0)*(.2+.6*Math.random()),y=b.y0+(b.y1-b.y0)*Math.random(),z=b.z0+(b.z1-b.z0)*(.2+.6*Math.random()),angle=i*2.39996;debris.push({entryId:entry.id,x,y,z,ox:x,oy:y,oz:z,vx:Math.cos(angle)*(2+Math.random()*3),vy:4+Math.random()*5,vz:Math.sin(angle)*(2+Math.random()*3),rx:Math.random()*6,ry:Math.random()*6,rz:0,color:rgb(p.color),scale:.48+Math.random()*.24,age:0});}if(impact)for(const d of debris.filter(d=>d.entryId===entry.id)){d.vx+=Math.sin(impact.heading)*impact.impulse;d.vz+=Math.cos(impact.heading)*impact.impulse;d.vy+=Math.min(1.8,impact.mass*.3);}
 for(const d of debris)GamePhysics.confineDebris(d,ensurePhysics());if(debris.length>220)debris.splice(0,debris.length-220);}
function smash(){
 if(!playing||gameOverlayOpen()||conversation||smashCooldown>0||controller?.state.building)return {smashed:0};
 const physics=ensurePhysics(),p=activeProfile(),w=GameWeapons.get(p.held);if(w.style==='fire')return fireWeapon();if(w.style==='magic')return castSpell();
 Object.assign(controller.state,{attack:w.duration,attackDuration:w.duration,attackWeapon:p.held});delete controller.state.attackImpact;smashCooldown=w.duration+.02;
 if(w.frames)pendingSmash={weapon:p.held,elapsed:0,last:{...controller.state}};
 else{const hit=physics.target(w.reach);pendingSmash=hit?{id:hit.id,group:hit.group,remaining:w.contact,reach:w.reach}:null;}
 dirty=true;return {smashed:0,swinging:true};
}
function stepSmash(dt){
 if(!pendingSmash)return;const strike=pendingSmash,physics=ensurePhysics();
 if(!strike.weapon){strike.remaining-=dt;if(strike.remaining>1e-6)return;pendingSmash=null;const hit=physics.target(strike.reach);if(!hit||hit.id!==strike.id&&(!strike.group||hit.group!==strike.group))return;impactEffect([physics.state.x+Math.sin(physics.state.heading)*2,physics.state.y+2.5,physics.state.z+Math.cos(physics.state.heading)*2]);breakHit(physics,hit);return;}
 const w=GameWeapons.get(strike.weapon),before=strike.elapsed,after=before+dt,state=physics.state;
 strike.elapsed=after;
 const end=Math.min(after,w.contact+.14),profile={...activeProfile(),held:strike.weapon};
 const sample=time=>{const blend=Math.max(0,Math.min(1,(time-before)/Math.max(.001,dt))),headingDelta=Math.atan2(Math.sin(state.heading-strike.last.heading),Math.cos(state.heading-strike.last.heading));return {...state,rigContact:state.rigContact,x:strike.last.x+(state.x-strike.last.x)*blend,y:strike.last.y+(state.y-strike.last.y)*blend,z:strike.last.z+(state.z-strike.last.z)*blend,heading:strike.last.heading+headingDelta*blend,attack:Math.max(0,w.duration-time),attackDuration:w.duration};};
 const expanded=p=>{const b=GamePhysics.bounds(p);return {x0:b.x0-w.radius,x1:b.x1+w.radius,y0:b.y0-w.radius,y1:b.y1+w.radius,z0:b.z0-w.radius,z1:b.z1+w.radius};};
 const candidates=pieces.filter(p=>{const b=GamePhysics.bounds(p);return b.x0<=state.x+w.reach+1&&b.x1>=state.x-w.reach-1&&b.z0<=state.z+w.reach+1&&b.z1>=state.z-w.reach-1&&b.y0<=state.y+6&&b.y1>=state.y-.3;});
 for(let time=Math.max(w.contact,before);time<=end+1e-6;time+=.008){
  const t=Math.min(time,end),previous=CharacterModel.strikePoints(profile,sample(Math.max(w.contact-.008,t-.008))),current=CharacterModel.strikePoints(profile,sample(t));
  // Full held-part boxes catch blade/head/shaft contact after an arm has been
  // constrained. Tip-only rays can miss a brick touched by the blade's side.
  if(state.rigContact){const sampled=sample(t),pose=CharacterModel.jointPose(sampled,false,profile),held=RigCollision.boxes(state.rigContact,pose,sampled,profile,p=>p.slot==='held'),contacts=RigCollision.scenery(state.rigContact,held).filter(c=>c.brick.y>0&&candidates.some(p=>p.id===c.brick.id));
   if(contacts.length){const hit=contacts[0];pendingSmash=null;state.attackImpact=t/w.duration;impactEffect(current[1],state.heading);breakHit(physics,pieces.find(p=>p.id===hit.brick.id),{heading:state.heading,impulse:w.impulse,mass:w.mass});return;}
  }
  for(const [start,finish] of [[previous[0],current[0]],[previous[1],current[1]],[current[0],current[1]]]){
   const delta=finish.map((v,k)=>v-start[k]),distance=Math.hypot(...delta),hit=GameWeapons.cast(start,delta.map(v=>v/Math.max(.0001,distance)),distance,candidates,expanded);
   if(!hit)continue;pendingSmash=null;state.attackImpact=t/w.duration;impactEffect(hit.point,state.heading);if(hit.piece.y>0)breakHit(physics,hit.piece,{heading:state.heading,impulse:w.impulse,mass:w.mass});return;
  }
 }
 strike.last={...state};if(after>=w.contact+.14)pendingSmash=null;
}
function breakHit(physics,hit,impact=null){
 const ids=new Set(pieces.filter(p=>p.y>0&&(p.id===hit.id||hit.group&&p.group===hit.group)).map(p=>p.id));let remaining=pieces.filter(p=>!ids.has(p.id)),check=inspect(remaining);if(!check.ok&&check.connected){remaining.forEach((p,i)=>{if(!check.connected.has(i))ids.add(p.id);});remaining=pieces.filter(p=>!ids.has(p.id));check=inspect(remaining);}if(!check.ok){gameMessage(check.reason,2);return {smashed:0};}
 const originals=clone(pieces.filter(p=>ids.has(p.id))),entry={id:brokenSerial++,originals,progress:0};remember();pieces=clone(remaining);broken.push(entry);makeDebris(entry,impact);renderRevision++;physics.replace(pieces);physicsRevision=renderRevision;savedPlayer={...controller.state};sync();persist();gameMessage(originals.length+' '+(originals.length===1?'brick':'bricks')+' smashed into loose pieces. Hold Rebuild nearby to put them back.',2.5);return {smashed:originals.length,damageId:entry.id};}
function cancelRebuild(){if(rebuildEntry)rebuildEntry.progress=0;rebuildEntry=null;if(controller)controller.state.building=false;q('#bb-rebuild-track').hidden=true;}
function rebuildStep(dt){
 const held=rebuildHeld||heldKeys.has('e'),entry=held?rebuildTarget():null,s=controller?.state;
 if(!entry){cancelRebuild();return;}
 if(!s.grounded||s.speed>.01){cancelRebuild();return;}
 // Never restore collision inside the player or send them back to spawn.
 if(!safeToRebuild(entry,s)){cancelRebuild();q('#bb-game-message').textContent='';return;}
 if(rebuildEntry!==entry){cancelRebuild();heroPending=null;heroConstruct=null;s.heroAction=null;s.heroTime=0;if(heroLift?.entry===entry){makeDebris(entry);heroLift=null;}rebuildEntry=entry;pendingSmash=null;pendingSpell=null;s.attack=0;s.reload=0;syncWeapon();}
 s.building=true;const bounds=damagedBounds(entry),heading=Math.atan2((bounds.x0+bounds.x1)/2-s.x,(bounds.z0+bounds.z1)/2-s.z),turn=Math.atan2(Math.sin(heading-s.heading),Math.cos(heading-s.heading));s.heading+=turn*(1-Math.exp(-dt*12));
 entry.progress=Math.min(1,(entry.progress||0)+dt/1.35);q('#bb-rebuild-track').hidden=false;q('#bb-rebuild-fill').style.width=Math.round(entry.progress*100)+'%';gameMessage('Rebuilding '+entry.originals.length+' bricks…',.1);
 if(entry.progress<1)return;
 const restored=[...pieces,...clone(entry.originals)],check=inspect(restored);if(!check.ok){cancelRebuild();rebuildHeld=false;heldKeys.delete('e');gameMessage('Rebuild blocked: '+check.reason,3);return;}
 remember();pieces=restored;broken=broken.filter(b=>b!==entry);debris=debris.filter(d=>d.entryId!==entry.id);renderRevision++;controller.replace(pieces,world);physicsRevision=renderRevision;cancelRebuild();pendingSmash=null;pendingSpell=null;savedPlayer={...s};sync();persist();gameMessage('Rebuilt! Every original brick is back in place.',2);
}
function stepDebris(dt){debrisClock+=dt;if(!debris.length)return;const physics=ensurePhysics();for(const d of debris){const entry=rebuildEntry?.id===d.entryId?rebuildEntry:null;if(entry){d.age+=dt;d.sleeping=false;const t=entry.progress;d.x+=(d.ox-d.x)*dt*(3+t*8);d.y+=(d.oy-d.y)*dt*(3+t*8);d.z+=(d.oz-d.z)*dt*(3+t*8);GamePhysics.confineDebris(d,physics);continue;}GamePhysics.stepDebrisPiece(d,dt,physics);}}
function gameFrame(dt){if(characterPreview){studioAnimationFrame(dt);return;}if(playing&&gameOverlayOpen())return;smashCooldown=Math.max(0,smashCooldown-dt);if(!playing){if(debris.length){const moving=debris.some(d=>!d.sleeping);stepDebris(dt);if(moving||debris.some(d=>!d.sleeping))dirty=true;}return;}ensurePhysics();ensureNPCs();const focused=!!conversation||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName),input={x:focused?0:(heldKeys.has('d')||heldKeys.has('arrowright')||touchMove.has('right')?1:0)-(heldKeys.has('a')||heldKeys.has('arrowleft')||touchMove.has('left')?1:0),z:focused?0:(heldKeys.has('w')||heldKeys.has('arrowup')||touchMove.has('forward')?1:0)-(heldKeys.has('s')||heldKeys.has('arrowdown')||touchMove.has('back')?1:0),run:heldKeys.has('shift')||runToggle||runHeld.size>0,jump:jumpRequested,vertical:focused?0:(heldKeys.has(' ')||jumpHeld.size>0?1:0)-(heldKeys.has('control')||descendHeld.size>0?1:0)};jumpRequested=false;heroMovement(input,dt,yaw,pitch);stepSmash(dt);combatStep(dt);heroStep(dt);target=[controller.state.x,controller.state.y+2.0*CharacterCatalog.heightScale(activeProfile()),controller.state.z];stepDebris(dt);npcFrame(dt);stepMapTeleports();if(!focused)rebuildStep(dt);else cancelRebuild();const hit=controller.target(GameWeapons.get(activeProfile().held).reach),damage=nearestBroken(),key=(hit?.id||'')+'|'+(damage?.id||'');if(clock>=gameMessageUntil&&(key!==lastGameTarget||gameMessageUntil>0)){q('#bb-game-message').textContent=damage?'':hit?'Object in reach · F / '+GameWeapons.get(activeProfile().held).action+' to break it':controller.state.running?'Running · Explore, jump, and find things to build':'Walking · Explore your world';gameMessageUntil=0;lastGameTarget=key;}saveClock+=dt;if(saveClock>=2){saveClock=0;savedPlayer={...controller.state};persist();}dirty=true;}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&gameScreenActive())return;if(gameOverlayOpen()||!playing||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||!q('#bb-dialog').hidden)return;if(e.target.tagName==='BUTTON'&&(e.key==='Enter'||[q('#bb-rebuild'),q('#bb-power-use'),q('#bb-descend')].includes(e.target)&&e.key===' '))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift',' ','f','e','r','t','q','control','escape'].includes(k)){e.preventDefault();heldKeys.add(k);if(conversation&&k==='escape'){closeConversation();return;}if(conversation&&k!=='t')return;if(k==='t'&&!e.repeat){if(conversation)closeConversation();else talkToNPC();}if(k===' '&&!e.repeat)jumpRequested=true;if(k==='f'&&!e.repeat)smash();if(k==='r'&&!e.repeat)reloadWeapon();if(k==='q'&&!e.repeat)usePower();if(k==='escape')stopPlaying();}},true);
document.addEventListener('keyup',e=>{heldKeys.delete(e.key.toLowerCase());});window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInput();});
for(const b of root.querySelectorAll('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))document.activeElement.blur();touchMove.add(b.dataset.move);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>touchMove.delete(b.dataset.move));}
q('#bb-run').addEventListener('pointerdown',e=>{e.preventDefault();q('#bb-run').setPointerCapture?.(e.pointerId);if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))document.activeElement.blur();runHeld.add(e.pointerId);q('#bb-run').setAttribute('aria-pressed','true');});for(const type of ['pointerup','pointercancel','lostpointercapture'])q('#bb-run').addEventListener(type,e=>{runHeld.delete(e.pointerId);q('#bb-run').setAttribute('aria-pressed',String(runToggle||runHeld.size>0));});q('#bb-run').addEventListener('click',e=>{if(e.detail>0)return;runToggle=!runToggle;q('#bb-run').setAttribute('aria-pressed',String(runToggle));});
q('#bb-jump').addEventListener('pointerdown',e=>{e.preventDefault();q('#bb-jump').setPointerCapture?.(e.pointerId);if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))document.activeElement.blur();jumpHeld.add(e.pointerId);jumpRequested=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])q('#bb-jump').addEventListener(type,e=>jumpHeld.delete(e.pointerId));q('#bb-jump').addEventListener('click',e=>{if(e.detail>0)return;jumpRequested=true;});q('#bb-smash').addEventListener('click',e=>{if(e.detail>0)return;smash();});
q('#bb-rebuild').addEventListener('pointerdown',e=>{e.preventDefault();q('#bb-rebuild').setPointerCapture?.(e.pointerId);rebuildHeld=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])q('#bb-rebuild').addEventListener(type,()=>{rebuildHeld=false;});q('#bb-rebuild').addEventListener('keydown',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();rebuildHeld=true;}});q('#bb-rebuild').addEventListener('keyup',()=>{rebuildHeld=false;});
function characterData(){return {items:characters.map(c=>({id:c.id,profile:CharacterCatalog.validate(c.profile)})),activeId:activeCharacterId};}
function parseCharacters(value){if(!value)return {items:[{id:1,profile:{...CharacterCatalog.defaults}}],activeId:1};if(!Array.isArray(value.items)||!value.items.length||value.items.length>24)throw Error('Choose 1–24 characters.');const ids=new Set(),items=value.items.map(c=>{if(!Number.isInteger(c.id)||c.id<1||ids.has(c.id))throw Error('Invalid character collection.');ids.add(c.id);return {id:c.id,profile:CharacterCatalog.validate(c.profile)};});return {items,activeId:ids.has(value.activeId)?value.activeId:items[0].id};}
function restoreAdventure(list){resetHero(true);shots=[];combatEffects=[];weaponAmmo.clear();weaponOwner='';pendingSmash=null;pendingSpell=null;const c=list.characters||parseCharacters();characters=c.items;activeCharacterId=c.activeId;broken=list.broken||[];brokenSerial=Math.max(0,...broken.map(e=>e.id))+1;savedPlayer=list.player||null;controller=null;physicsRevision=-1;restoreNPCs(list.npcs);debris=[];for(const entry of broken)makeDebris(entry);syncCharacter();}
function registerCharacterTools(register){
 register({name:'configure_lego_character',description:'Edit every option of the active minifigure, or apply a preset. Shows the live character studio.',inputSchema:{type:'object',properties:{preset:{type:'string',enum:Object.keys(CharacterCatalog.presets)},profile:{type:'object',properties:Object.fromEntries([...Object.entries(CharacterCatalog.choices).map(([k,v])=>[k,{type:'string',enum:v}]),...CharacterCatalog.colorFields.map(k=>[k,{type:'string',pattern:'^#[0-9a-fA-F]{6}$'}]),['name',{type:'string',maxLength:32}],...Object.entries(CharacterCatalog.rangeFields).map(([key,{max}])=>[key,{type:'integer',minimum:0,maximum:max}])]),additionalProperties:false}},additionalProperties:false},execute(input){const base=input.preset?CharacterCatalog.preset(input.preset):activeProfile(),look=input.profile?.costume?SuperPowers.dress(base,input.profile.costume):base,profile=CharacterCatalog.validate({...look,...input.profile});remember();activeCharacter().profile=profile;showCharacterStudio();persist();draw();return {character:profile,options:CharacterCatalog.choices};}});
 register({name:'explore_lego_world',description:'Start or stop playing as the active character in this world, with collision, jumping, smashing and rebuilding.',inputSchema:{type:'object',properties:{playing:{type:'boolean'}},required:['playing'],additionalProperties:false},execute(input){if(input.playing)startPlaying();else stopPlaying();draw();return {playing,player:controller?{...controller.state}:null};}});
 register({name:'control_lego_character',description:'Control the playable character using the same movement and action functions as keyboard and touch controls. Positive forward moves into the scene; right is camera-relative. A smash with no seconds advances to contact; seconds: 0 starts its windup. Rebuild restores nearby smashed originals after a hold.',inputSchema:{type:'object',properties:{weapon:{type:'string',enum:['None',...Object.keys(GameWeapons.catalog)]},spell:{type:'string',enum:Object.keys(GameMagic.spells)},power:{type:'string',enum:Object.keys(SuperPowers.powers)},usePower:{type:'boolean'},vertical:{type:'number',minimum:-1,maximum:1},lookPitch:{type:'number',minimum:-1.35,maximum:1.35},reload:{type:'boolean'},forward:{type:'number',minimum:-1,maximum:1},right:{type:'number',minimum:-1,maximum:1},run:{type:'boolean'},jump:{type:'boolean'},smash:{type:'boolean'},rebuild:{type:'boolean'},seconds:{type:'number',minimum:0,maximum:5}},additionalProperties:false},execute(input){if(!playing)throw Error('Start exploration first.');if(input.weapon)equipWeapon(input.weapon);if(input.spell)equipSpell(input.spell);if(input.power)equipPower(input.power);const seconds=Math.max(0,Math.min(5,input.seconds===undefined&&input.smash?(GameWeapons.get(activeProfile().held).contact||.18)+.02:Number(input.seconds===undefined&&input.usePower?1:input.seconds)||0));if(input.usePower)usePower();if(input.lookPitch!==undefined)pitch=clamp(input.lookPitch,-1.35,1.35);if(input.reload)reloadWeapon();if(input.smash)smash();for(let t=0;t<seconds;t+=.025){heroMovement({x:clamp(input.right||0,-1,1),z:clamp(input.forward||0,-1,1),run:!!input.run,jump:!!input.jump&&t===0,vertical:clamp(input.vertical||0,-1,1)},Math.min(.025,seconds-t),yaw,pitch);stepSmash(Math.min(.025,seconds-t));combatStep(Math.min(.025,seconds-t));heroStep(Math.min(.025,seconds-t));rebuildHeld=!!input.rebuild;rebuildStep(Math.min(.025,seconds-t));stepDebris(.025);npcFrame(.025);if(stepMapTeleports())break;smashCooldown=Math.max(0,smashCooldown-.025);}rebuildHeld=false;if(!input.rebuild)cancelRebuild();target=[controller.state.x,controller.state.y+2,controller.state.z];savedPlayer={...controller.state};persist();draw();return {player:{...controller.state},pieces:pieces.length,damagedObjects:broken.length,power:activeProfile().power,powerStatus:heroStatus()};}});
}
