const NPCWorld=(()=>{
'use strict';
const roles={forest:['Explorer','Forest ranger'],rainforest:['Rainforest guide','Nature guide'],city:['City worker','Chef'],prairie:['Runner','Explorer'],mountains:['Skier','Explorer'],volcanoes:['Explorer','Nature guide'],desert:['Cowboy','Explorer'],beach:['Beach swimmer','Summer outfit'],highway:['City worker','Detective'],castle_outside:['Knight','Wizard'],castle_inside:['Princess','Knight']},names=['Maya','Finn','Ruby','Eli','Zoe','Theo','Avery','Luca','Nora','Kai','Iris','Leo','Sam','Ada'];
function rng(seed){let state=seed>>>0;return ()=>{state+=0x6D2B79F5;let t=state;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
function populate(pieces,world,player=null){if(!pieces.length)return [];const random=rng((world?.config?.seed||73521)^0x57ab281),base=new GamePhysics.Controller(pieces,world),ground=pieces.filter(p=>p.y===0),regions=world?.regions||[],count=Math.min(14,Math.max(4,(world?.config?.biomes.length||1)*2)),npcs=[];
 for(let i=0;i<count;i++){let pos=null;base.state.height=CharacterCatalog.choices.height[i%CharacterCatalog.choices.height.length];const region=regions[i%Math.max(1,regions.length)],biome=region?.biome||'city';for(let tries=0;tries<160;tries++){let x,z;if(i===0&&player&&tries<24){const a=random()*6.283,d=2.1+random()*.9;x=player.x+Math.sin(a)*d;z=player.z+Math.cos(a)*d;}else if(region){x=region.x+.7+random()*(region.width-1.4);z=region.z+.7+random()*(region.depth-1.4);}else{const p=ground[Math.floor(random()*ground.length)],b=GamePhysics.bounds(p);x=b.x0+.5+random()*Math.max(.1,b.x1-b.x0-1);z=b.z0+.5+random()*Math.max(.1,b.z1-b.z0-1);}const y=base.floor(x,z,1.35);if(y!==null&&base.clear(x,y,z)&&npcs.every(n=>Math.hypot(n.state.x-x,n.state.z-z)>1.65)&&(!player||Math.hypot(x-player.x,z-player.z)>1.65)){pos={x,y,z};break;}}if(!pos)continue;
  const picks=roles[biome]||roles.city,role=picks[i%picks.length],preset=CharacterCatalog.presets[role]?role:'Explorer',profile=CharacterCatalog.preset(preset);profile.name=names[i%names.length];profile.gender=i%2?'Female':'Male';if(profile.gender==='Female'&&profile.hair==='Side part')profile.hair=['Ponytail','Bob','Bun'][i%3];profile.height=CharacterCatalog.choices.height[i%CharacterCatalog.choices.height.length];profile.expression=['Smile','Big grin','Peaceful'][i%3];const ctl=Object.create(GamePhysics.Controller.prototype);Object.assign(ctl,{pieces:base.pieces,bins:base.bins,world:base.world,area:base.area,state:{...base.state,...pos,height:profile.height,heading:random()*6.283,phase:0,speed:0,vy:0,grounded:true},spawnPoint:{...pos}});npcs.push({id:i+1,biome,role,profile,controller:ctl,state:ctl.state,home:pos,wait:random()*2,walking:false,direction:random()*6.283,random});
 }return npcs;
}
function restore(saved,pieces,world=null){if(!Array.isArray(saved)||saved.length>20)return [];const base=new GamePhysics.Controller(pieces,world),ids=new Set(),result=[];for(const n of saved){if(!Number.isInteger(n.id)||n.id<1||ids.has(n.id))throw Error('Invalid world character.');ids.add(n.id);if(!n.state||!['x','y','z','heading'].every(k=>Number.isFinite(n.state[k]))||Math.abs(n.state.x)>300||Math.abs(n.state.z)>300||n.state.y<0||n.state.y>130)throw Error('Invalid world character position.');const profile=CharacterCatalog.validate(n.profile),state={...base.state,x:n.state.x,y:n.state.y,z:n.state.z,heading:n.state.heading,height:profile.height,speed:0,phase:0,vy:0,grounded:true},ctl=Object.create(GamePhysics.Controller.prototype);Object.assign(ctl,{pieces:base.pieces,bins:base.bins,world:base.world,area:base.area,state,spawnPoint:{x:state.x,y:state.y,z:state.z}});ctl.repairPosition();if(!ctl.clear(state.x,state.y,state.z))ctl.spawn();result.push({id:n.id,profile,biome:typeof n.biome==='string'?n.biome.slice(0,32):'city',role:typeof n.role==='string'?n.role.slice(0,32):'Explorer',controller:ctl,state,home:{x:state.x,y:state.y,z:state.z},random:rng(n.id*3371),wait:1,walking:false,direction:state.heading});}return result;}
function sync(npcs,pieces,world=null){const base=new GamePhysics.Controller(pieces,world);for(const n of npcs){n.controller.pieces=base.pieces;n.controller.bins=base.bins;n.controller.world=base.world;n.controller.area=base.area;const repaired=n.controller.repairPosition();if(!n.controller.clear(n.state.x,n.state.y,n.state.z)){n.controller.spawn();n.home={x:n.state.x,y:n.state.y,z:n.state.z};}else if(repaired)n.home={x:n.state.x,y:n.state.y,z:n.state.z};}}
function connect(npcs,player){const state=player?.state||player,actors=[...npcs.map(n=>n.state),...(state?[state]:[])];for(const n of npcs)n.controller.setActors(actors);if(player?.state)player.setActors(actors);}
function step(npcs,dt,player,talkingId=null){connect(npcs,player);for(const n of npcs){const s=n.state;if(s.frozen>0){s.frozen=Math.max(0,s.frozen-dt);s.speed=0;if(s.rigContact)s.rigContact.clock=(s.rigContact.clock||0)+dt;continue;}if(n.id===talkingId||Math.hypot(s.x-player.x,s.z-player.z)<1.8){n.controller.step({x:0,z:0},dt,0);if(n.id===talkingId)s.heading=Math.atan2(player.x-s.x,player.z-s.z);continue;}n.wait-=dt;if(n.wait<=0){n.walking=!n.walking;n.wait=n.walking?1+n.random()*2:1.5+n.random()*3;n.direction=n.random()*6.283;}if(n.walking){const dx=Math.sin(n.direction)*.38,dz=Math.cos(n.direction)*.38,fx=s.x+dx*.9,fz=s.z+dz*.9,f=n.controller.floor(fx,fz,s.y+.46);if(f===null||f<s.y-.5||Math.hypot(fx-n.home.x,fz-n.home.z)>4.5||!n.controller.clear(fx,s.y,fz)){n.direction+=Math.PI*.75;n.wait=.25;n.controller.step({x:0,z:0},dt,0);}else n.controller.step({x:dx,z:-dz},dt,0);}else n.controller.step({x:0,z:0},dt,0);}}
function nearest(npcs,player,max=3.7){let best=null,d=max;for(const n of npcs){const dist=Math.hypot(player.x-n.state.x,player.z-n.state.z);if(dist<d&&Math.abs(player.y-n.state.y)<2.3){d=dist;best=n;}}return best;}
function serialize(npcs){return npcs.map(n=>({id:n.id,biome:n.biome,role:n.role,profile:CharacterCatalog.validate(n.profile),state:{x:n.state.x,y:n.state.y,z:n.state.z,heading:n.state.heading}}));}
function reply(n,text,world,environment,damageCount=0){const t=String(text||'hello').toLowerCase(),place=n.biome.replaceAll('_',' '),name=n.profile.name;
 if(/bye|see you|goodbye/.test(t))return 'See you around. Leave a few bricks for the rest of us!';
 if(/who|name|yourself/.test(t))return "I'm "+name+', a '+n.role.toLowerCase()+'. I like wandering around the '+place+'. What are you building today?';
 if(/rebuild|repair|destroy|smash|broken/.test(t))return damageCount?'There are '+damageCount+' damaged creations nearby. Follow the glowing area: its arrow points to the creation you can restore. Stand clear of the missing bricks and hold E or Rebuild until the bar fills.':'Face a nearby creation and press F or Smash. Then follow the glowing build area and hold E to put the bricks back. The ground stays in place.';
 if(/jump|run|walk|control/.test(t))return 'Use WASD or the directional pad to move. Hold Shift or Run to go faster. Jump still works while you are running. Drag the view to look around.';
 if(/weather|rain|snow|night|day|sky/.test(t)){const weather=environment.snowing?'Snow is falling':environment.rain?'It is raining':environment.snow?'Snow covers the bricks':'The sky is clear';return weather+', and it is '+environment.time+'. You can change the sky and weather in the World tab.';}
 if(/build|tips|brick|connect/.test(t))return 'Switch to Bricks to add your own pieces. Put studs under your build and leave enough room to move through it. Smooth tiles look great on paths, but they do not have studs on top.';
 if(/photo|draw|paint|character|clothes/.test(t))return 'The character studio lets you paint each part and import a whole-person photo. Clothing and accessories are editable, so try a look that suits this place.';
 if(/place|world|here|about|forest|city|castle|beach|mountain|volcano|desert/.test(t)){const facts={forest:'Those trees make good landmarks. Keep a gap between trunks for a path.',rainforest:'The canopy is thick here. Watch for open spaces between the trees.',city:'I like the city streets. Buildings make excellent jumping practice.',prairie:'There is room here for a farm, a garden, or a huge racecourse.',mountains:'These snowy peaks tower above the trees. Find a ledge or use flight to reach the summit.',volcanoes:'The dark slopes surround a crater of orange lava bricks. We can build a lookout on the rim.',desert:'Sand, cacti, and long views. A little shade would be a useful build.',beach:'Sand and water bricks make a good starting point for a boardwalk.',highway:'The road connects the districts. We could use a few more places to stop.',castle_outside:'Those towers look impressive, but every one is made of separate bricks.',castle_inside:'This hall could use a secret room. Leave us a doorway when you build one.'};return facts[n.biome]||'This is our shared brick world. There is always room for another idea.';}
 if(/hello|hi\b|hey|greet/.test(t))return 'Hello! I am '+name+'. Want to know about this place, building, or exploring?';
 return ['That sounds like a good project. Tell me about the world you want to build.','I can help with building, controls, weather, or rebuilding broken bricks. What would you like to know?','I have been looking around the '+place+'. What do you think we should build here?'][Math.min(2,Math.floor(n.random()*3))];
}
return {populate,restore,sync,connect,step,nearest,serialize,reply};
})();
