const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
function boot(){
const tools=new Map(),stored=new Map(),buffers=[];
const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,getAttribLocation:(_,s)=>s,getUniformLocation:(_,s)=>s,createBuffer:()=>({}),createShader:()=>({}),createProgram:()=>({}),bufferData:(_,a)=>{assert(a.length>0);for(const v of a)assert(Number.isFinite(v));buffers.push(a.length);},drawArrays:(_,start,count)=>assert(count>0)}, {get:(o,k)=>k in o?o[k]:(k.toUpperCase()===k?1:()=>{})});
const elements={};let doc;
class Element{constructor(tag='DIV'){this.tagName=tag;this.dataset={};this.value='';this.checked=false;this.children=[];this.handlers={};this.style={setProperty(){}};this.textContent='';this.hidden=false;this.disabled=false;}addEventListener(e,f){this.handlers[e]=f;}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}appendChild(b){this.children.push(b);}replaceChildren(){this.children=[];}getBoundingClientRect(){return{width:780,height:570,left:0,top:0};}focus(){doc.activeElement=this;}select(){}click(){this.handlers.click?.({target:this});}querySelector(s){return this.children.find(c=>c.tagName===s.toUpperCase())||new Element(s.toUpperCase());}querySelectorAll(){return this.children;}setPointerCapture(){}}
const ids=[...fs.readFileSync(path.join(__dirname,'../../dist/index.html'),'utf8').matchAll(/id="([^"]+)"/g)].map(x=>x[1]);for(const id of ids)elements['#'+id]=new Element();
elements['#bb-canvas'].tagName='CANVAS';elements['#bb-canvas'].getContext=()=>gl;elements['#bb-dialog'].hidden=true;elements['#bb-data'].tagName='TEXTAREA';
const buttons=['add','select','orbit'].map(name=>{const b=new Element('BUTTON');b.dataset.tool=name;return b;});
const root={dataset:{},querySelector:s=>{assert(elements[s],s);return elements[s];},querySelectorAll:s=>s==='[data-tool]'?buttons:[],addEventListener:(e,f)=>elements['#brick-builder'].addEventListener(e,f)};
doc={addEventListener(){},activeElement:null,getElementById:()=>root,createElement:tag=>new Element(tag.toUpperCase()),modelContext:{registerTool:t=>tools.set(t.name,t)}};
const context={document:doc,window:{devicePixelRatio:1,addEventListener(){},location:{reload(){}}},localStorage:{setItem:(k,v)=>stored.set(k,v),getItem:k=>stored.get(k)},ResizeObserver:class{observe(){}},requestAnimationFrame:()=>{},AbortController,console,Blob,URL,setTimeout,navigator:{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../dist/index.html'),'utf8').split('<script>')[1].split('</script>')[0],context);
return {tools,elements,buttons,buffers,stored,read:()=>tools.get('read_brick_build').execute(),add:a=>tools.get('place_bricks').execute({pieces:a}),move:p=>tools.get('move_brick').execute(p),fire:(id,event='click',value)=>elements['#'+id].handlers[event]?.({target:elements['#'+id],...value})};
}

const b=boot(),call=(name,args)=>b.tools.get(name).execute(args),read=b.read;
let catalog=call('configure_lego_character',{preset:'Explorer'}).options,count=0;
for(const [field,options] of Object.entries(catalog))for(const value of options){call('configure_lego_character',{profile:{[field]:value}});count++;}
for(const preset of ['Explorer','Knight','Astronaut','Pirate','Wizard','Princess','City worker','Beach swimmer','Runner','Rockstar','Skier','Cowboy','Detective','Chef','Rainforest guide','Summer outfit','Bikini set','Loungewear'])call('configure_lego_character',{preset});
const before=JSON.stringify(read().characters);assert.throws(()=>call('configure_lego_character',{profile:{hair:'invalid'}}));assert.equal(JSON.stringify(read().characters),before);
b.fire('bb-character-new');b.fire('bb-character-copy');assert.equal(read().characters.items.length,3);
const ground={id:1,rows:8,cols:8,turn:0,x:-4,z:-4,y:0,kind:'plate',color:3};const tower=[1,4,7].map((y,i)=>({id:2+i,rows:2,cols:2,turn:0,x:-1,z:-3,y,kind:'brick',color:8,group:'tree-test'}));const original=[ground,...tower];
function load(obj){b.fire('bb-open');b.elements['#bb-data'].value=JSON.stringify(obj);b.fire('bb-load-code');assert.equal(b.elements['#bb-dialog-message'].textContent,'');}
load({format:'brick-builder',version:3,pieces:original,characters:read().characters,world:null});const spawned=call('explore_lego_world',{playing:true}).player;assert.equal(spawned.x,0);assert.equal(spawned.z,0);assert.equal(spawned.y,.4);
call('control_lego_character',{forward:1,seconds:.6});let player=read().player;assert(player.z>-.65,'solid tower blocks movement');assert(player.grounded);
call('control_lego_character',{jump:true,seconds:.2});assert(read().player.y>1.4,'jump lifts the figure');call('control_lego_character',{seconds:1.2});assert(Math.abs(read().player.y-.4)<.001,'gravity lands on terrain');
call('control_lego_character',{smash:true});assert.equal(read().pieces.length,1);assert.equal(read().broken.length,1);assert.equal(read().broken[0].originals.length,3);
const smashedSave=JSON.stringify(read());call('control_lego_character',{rebuild:true,seconds:1.5});assert.equal(read().broken.length,0);assert.equal(read().pieces.length,4);assert.deepStrictEqual(JSON.parse(JSON.stringify(read().pieces.slice().sort((a,b)=>a.id-b.id))),original);
call('explore_lego_world',{playing:false});load(JSON.parse(smashedSave));assert.equal(read().broken.length,1);call('explore_lego_world',{playing:true});call('control_lego_character',{rebuild:true,seconds:1.5});assert.equal(read().pieces.length,4,'rebuild works after saved reload');
const laneNPCs=[{id:1,profile:read().characters.items[0].profile,state:{x:-2,y:.4,z:-2,heading:0}}];load({format:'brick-builder',version:3,pieces:[ground],characters:read().characters,npcs:laneNPCs});const walkStart=call('explore_lego_world',{playing:true}).player;call('control_lego_character',{right:1,seconds:.2});const walkDist=Math.abs(read().player.x-walkStart.x);call('explore_lego_world',{playing:false});load({format:'brick-builder',version:3,pieces:[ground],npcs:laneNPCs});const runStart=call('explore_lego_world',{playing:true}).player;call('control_lego_character',{right:1,run:true,seconds:.2});const runDist=Math.abs(read().player.x-runStart.x);assert(runDist>walkDist*1.8,'run is faster than walk');
call('control_lego_character',{forward:1,run:true,seconds:5});call('control_lego_character',{seconds:2});assert(read().player.y>=.399,'falling off edge respawns');
call('explore_lego_world',{playing:false});b.fire('bb-save');const exported=JSON.parse(b.elements['#bb-data'].value);assert.equal(exported.version,4);assert(exported.characters.items.length);b.fire('bb-dialog-close');load({format:'brick-builder',version:1,pieces:[ground]});assert.equal(read().pieces.length,1,'legacy projects open');
console.log('PASS: '+count+' appearance/asset choices and 18 presets render finite geometry; editable roster; invalid options are atomic; walking/running, collision, jump/gravity, grouped smash, exact rebuild, save/reload damage and legacy imports.');
