const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const ctx={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../src/legacy/game-magic.js'),'utf8')+';globalThis.M=GameMagic;',ctx);const M=ctx.M;
assert.equal(Object.keys(M.spells).length,6);assert.equal(new Set(Object.values(M.spells).map(s=>s.pattern)).size,6);assert.equal(new Set(Object.values(M.spells).map(s=>JSON.stringify(s.colors))).size,6);
const bounds={x0:-16,x1:16,z0:-16,z1:16},signatures=new Set();
for(const name of Object.keys(M.spells)){const effects=[...M.trail(name,[15.8,2,15.8],[0,0,-1],.3),...M.burst(name,[15.8,2,15.8])];signatures.add(JSON.stringify(effects.map(e=>[e.position,e.velocity,e.color])));assert(effects.length<80);for(let i=0;i<30;i++)for(const e of effects){M.step(e,.05,bounds);assert(e.position.every(Number.isFinite)&&e.velocity.every(Number.isFinite));assert(e.position[0]<=15.94&&e.position[2]<=15.94&&e.position[1]>=.07);}assert(effects.every(e=>e.life<=0),'particles expire');}assert.equal(signatures.size,6,'each spell has a distinct spatial particle pattern');
let source=fs.readFileSync(path.join(__dirname,'characters.cjs'),'utf8').split('const b=boot(),call=')[0];source=source.replace(".split('</script>')[0],context)",".split('</script>')[0].replace(/\\}\\)\\(\\);\\s*$/, 'globalThis.magicDebug=()=>({pendingSpell,shots,combatEffects,controller});})();'),context)").replace('return {tools,elements,buttons,buffers,stored,','return {debug:context.magicDebug,tools,elements,buttons,buffers,stored,');const bootCtx={require,__dirname,console,AbortController,Blob,URL,setTimeout};vm.runInNewContext(source+';globalThis.boot=boot;',bootCtx);const b=bootCtx.boot(),call=(n,v)=>b.tools.get(n).execute(v);
const catalog={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../src/legacy/character-catalog.js'),'utf8')+';globalThis.C=CharacterCatalog;',catalog);
const ground=[];for(const x of [-16,-8,0,8])for(const z of [-16,-8,0,8])ground.push({id:100+ground.length,x,z,y:0,cols:8,rows:8,turn:0,kind:'plate',color:3});
const tower=(start,x,z,group)=>[1,4,7,10].map((y,i)=>({id:start+i,x,z,y,cols:2,rows:2,turn:0,kind:'brick',color:8,group})),original=[...ground,...tower(1,-1,-8,'A'),...tower(10,1,-7,'B'),...tower(20,-1,-14,'far')];
function load(){b.fire('bb-open');b.elements['#bb-data'].value=JSON.stringify({format:'brick-builder',version:4,pieces:original,player:{x:0,y:.4,z:0,heading:Math.PI},npcs:[{id:1,profile:catalog.C.defaults,state:{x:8,y:.4,z:6,heading:0}}]});b.fire('bb-load-code');assert.equal(b.elements['#bb-dialog-message'].textContent,'');call('explore_lego_world',{playing:true});}
for(const name of Object.keys(M.spells)){
 load();call('control_lego_character',{weapon:'Wand',spell:name,smash:true,seconds:.15});assert(b.debug().pendingSpell,'wand charges before launch');assert.equal(b.read().pieces.length,original.length,'no damage during charge');assert.equal(b.elements['#bb-smash'].textContent,'Cast');assert(!b.elements['#bb-spell-controls'].hidden);assert(b.elements['#bb-reload'].hidden);
 let burst=false;for(let i=0;i<30;i++){call('control_lego_character',{seconds:.05});if(b.read().broken.length){burst=true;break;}}
 assert(burst,name+' impacts a creation');assert.equal(b.read().pieces.filter(p=>p.group==='far').length,4,'a foreground hit shields distant creations');assert(b.read().broken.some(e=>e.originals.some(p=>p.group==='A')),name+' shatters the target');assert(b.read().broken.some(e=>e.originals.some(p=>p.group==='B')),name+' blast reaches a neighboring creation');assert(b.debug().combatEffects.some(e=>e.kind==='magic'&&e.color.every((v,k)=>v===M.get(name).colors[0][k])),'impact renders the selected palette');assert.equal(b.read().characters.items.find(c=>c.id===b.read().characters.activeId).profile.spell,name,'spell choice persists in character data');
 call('control_lego_character',{forward:1,seconds:.85});const before=b.read().player;call('control_lego_character',{rebuild:true,seconds:4});assert.equal(b.read().pieces.length,original.length,name+' restores all exploded originals');const after=b.read().player;assert(Math.hypot(after.x-before.x,after.z-before.z)<.00001,'rebuilding preserves player position');
}
load();call('control_lego_character',{weapon:'Wand',spell:'Prism Nova',smash:true,seconds:.10});call('control_lego_character',{weapon:'Club',seconds:1});assert.equal(b.read().pieces.length,original.length,'changing weapon cancels a charging spell');assert.equal(b.debug().shots.length,0);
call('control_lego_character',{weapon:'Wand',smash:true,run:true,right:1,jump:true,seconds:.3});assert(b.read().player.y>1,'casting permits simultaneous running and jumping');assert(b.debug().combatEffects.length<=600&&b.debug().shots.length<=24,'effects and projectiles remain bounded');call('explore_lego_world',{playing:false});assert.equal(b.debug().pendingSpell,null);assert.equal(b.debug().shots.length,0);assert.equal(b.debug().combatEffects.length,0);
assert.throws(()=>call('configure_lego_character',{profile:{spell:'Not a spell'}}));
console.log('PASS: six distinct palettes and particle patterns, finite bounded effects, charge/flick/projectile impacts, multi-creation blasts, obstruction/range isolation, exact rebuilds, saved spell choices, cancellation, and simultaneous run/jump/cast.');
