const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
let source=fs.readFileSync(path.join(__dirname,'characters.cjs'),'utf8').split('const b=boot(),call=')[0];
source=source.replace('function boot(){','function boot(saved){').replace('stored=new Map(),buffers=[];',"stored=new Map(saved?[['lego-free-build-v1',saved]]:[]),buffers=[];");
source=source.replace("split('</script>')[0],context)","split('</script>')[0].replace(/\\}\\)\\(\\);\\s*$/, 'globalThis.mapQA={get:()=>({playing,characterPreview,mapPreviewReturn,mapPlacing,controller}),tick:dt=>{clock+=dt;gameFrame(dt);mapPortalFrame();},move:p=>Object.assign(ensurePhysics().state,p),draw,camera};})();'),context)").replace('return {tools,elements,buttons,buffers,stored,','return {qa:context.mapQA,tools,elements,buttons,buffers,stored,');
const ctx={require,__dirname,console,AbortController,Blob,URL,setTimeout};vm.runInNewContext(source+';globalThis.boot=boot;',ctx);
const b=ctx.boot(),el=id=>b.elements['#'+id],call=(n,v)=>b.tools.get(n).execute(v),manage=v=>call('manage_lego_maps',v),read=()=>JSON.parse(JSON.stringify(b.read()));
function load(obj){b.fire('bb-open');el('bb-data').value=JSON.stringify(obj);b.fire('bb-load-code');assert.equal(el('bb-dialog-message').textContent,'');}
const config={biomes:['prairie'],time:'noon',rain:false,snow:false,snowing:false,size:16,seed:372};
const ground={id:1,rows:8,cols:8,turn:0,x:-4,z:-4,y:0,kind:'plate',color:3},tower=[1,4,7].map((y,i)=>({id:2+i,rows:2,cols:2,turn:0,x:-1,z:-3,y,kind:'brick',color:8,group:'tower'}));
load({format:'brick-builder',version:3,pieces:[ground,...tower]});assert.equal(read().maps.maps.length,1,'legacy single worlds migrate');
call('explore_lego_world',{playing:true});call('control_lego_character',{smash:true});assert.equal(read().broken.length,1);const damage=read().broken;
const first=read().maps.activeId,second=manage({action:'create',name:'Prairie',config}).result;assert.notEqual(first,second);assert.equal(read().maps.maps.length,2);assert.equal(read().world.config.biomes[0],'prairie');assert.equal(read().broken.length,0);
const prairiePieces=read().pieces,prairieNPCs=read().npcs,link=manage({action:'connect',mapId:first,spawnId:1}).result;
assert.equal(read().maps.links.length,1);assert.equal(el('bb-map-overview').children.length,2);assert.equal(el('bb-map-links').children.length,1);
assert.throws(()=>manage({action:'connect',mapId:first,spawnId:1}),/already connected/);
manage({action:'switch',mapId:first});assert.equal(read().pieces.length,1);assert.deepStrictEqual(read().broken,damage,'map damage survives switching');
manage({action:'preview',mapId:second,spawnId:1});assert.equal(read().maps.activeId,second);assert.equal(b.qa.get().mapPreviewReturn,first);assert(!el('bb-map-preview').hidden);assert(!b.qa.get().playing);b.fire('bb-map-preview-back');assert.equal(read().maps.activeId,first);assert.equal(b.qa.get().mapPreviewReturn,null);
call('configure_lego_character',{profile:{hair:'Ponytail',height:'Tall'}});manage({action:'switch',mapId:second});assert.equal(read().characters.items[0].profile.hair,'Ponytail','characters shared across maps');assert.deepStrictEqual(read().pieces,prairiePieces,'terrain preserved');assert.deepStrictEqual(read().npcs.map(n=>[n.state.x,n.state.z]),prairieNPCs.map(n=>[n.state.x,n.state.z]),'NPC positions preserved');
const spawn=read().maps.maps.find(m=>m.id===second).spawns[0];call('explore_lego_world',{playing:true});b.qa.move({...spawn,grounded:true});b.qa.tick(2);assert(!el('bb-map-travel').hidden,'gate prompts only nearby');b.fire('bb-map-travel');assert.equal(read().maps.activeId,first);assert(b.qa.get().playing,'travel continues exploring');assert(el('bb-map-travel').hidden,'arrival debounce prevents bounce');const player=read().player,c=b.qa.get().controller;assert(c.contains(player.x,player.z)&&c.clear(player.x,player.y,player.z),'arrival fits complete actor rig and does not overlap NPCs');assert.throws(()=>manage({action:'travel',linkId:link}),/Walk to/);b.qa.tick(2);assert(!el('bb-map-travel').hidden,'return route offered after cooldown');manage({action:'travel',linkId:link});assert.equal(read().maps.activeId,second);assert.equal(read().characters.items[0].profile.height,'Tall');
manage({action:'switch',mapId:first});const pointId=manage({action:'addSpawn',name:'Side gate'}).result;manage({action:'setSpawn',spawnId:pointId,position:{x:2,y:.4,z:2,heading:1}});assert.equal(read().maps.maps[0].spawns.length,2);manage({action:'connect',mapId:second,spawnId:1,twoWay:false});assert.equal(read().maps.links[1].twoWay,false);
const before=JSON.stringify(read());assert.throws(()=>manage({action:'setSpawn',position:{x:200,y:.4,z:0}}),/inside/);assert.equal(JSON.stringify(read()),before,'invalid spawn placement is atomic');
const third=manage({action:'copy',name:'Tower copy'}).result;assert.equal(read().maps.maps.length,3);assert.deepStrictEqual(read().broken,damage);b.fire('bb-undo');assert.equal(read().maps.maps.length,2,'map creation undo restores collection');b.fire('bb-redo');assert.equal(read().maps.activeId,third);assert.equal(read().maps.maps.length,3);
const save=JSON.stringify(read());load(JSON.parse(save));assert.equal(read().maps.maps.length,3);assert.equal(read().maps.links.length,2);manage({action:'switch',mapId:second});assert.deepStrictEqual(read().pieces,prairiePieces,'inactive terrain round-trips');manage({action:'switch',mapId:first});assert.deepStrictEqual(read().broken,damage,'inactive damage round-trips');
b.fire('bb-spawn-place');assert(b.qa.get().mapPlacing);b.fire('bb-canvas','pointerdown',{pointerId:1,clientX:390,clientY:285,button:0});b.fire('bb-canvas','pointerup',{pointerId:1,clientX:390,clientY:285});assert(!b.qa.get().mapPlacing,'terrain tap places a safe point');assert(el('bb-map-message').textContent.includes('Spawn placed'));
const valid=read();for(const mutate of [p=>p.maps.links[0].to.spawnId=999,p=>p.maps.maps[1].spawns[0].x=299,p=>p.maps.maps[1].id=p.maps.maps[0].id,p=>p.maps.maps[1].build.maps={},p=>p.maps.maps[1].build.pieces[0].rows=999]){const invalid=JSON.parse(JSON.stringify(valid));mutate(invalid);const old=JSON.stringify(read());b.fire('bb-open');el('bb-data').value=JSON.stringify(invalid);b.fire('bb-load-code');assert(el('bb-dialog-message').textContent,'invalid network rejected');assert.equal(JSON.stringify(read()),old,'invalid import leaves all maps untouched');b.fire('bb-dialog-close');}
const reloaded=ctx.boot(save);assert.equal(reloaded.read().maps.maps.length,3,'device autosave restores all maps after reload');assert.equal(reloaded.read().maps.links.length,2);
b.fire('bb-spawn-delete');assert.equal(read().maps.links.length,1,'removing a spawn removes its links');b.fire('bb-undo');assert.equal(read().maps.links.length,2);b.fire('bb-map-delete');assert.equal(read().maps.maps.length,2);assert(read().maps.links.every(l=>l.to.mapId!==first&&l.from.mapId!==first),'removed maps leave no dangling routes');b.fire('bb-undo');assert.equal(read().maps.maps.length,3);assert.equal(read().maps.links.length,2);
const fork=ctx.boot(save),fm=v=>fork.tools.get('manage_lego_maps').execute(v);fm({action:'switch',mapId:first});const branchId=fm({action:'connect',mapId:third,spawnId:1}).result;fork.tools.get('explore_lego_world').execute({playing:true});fork.qa.move(fork.read().maps.maps.find(m=>m.id===first).spawns[0]);fork.qa.tick(2);assert(fork.elements['#bb-map-route'].children.length>=2,'forked gates offer every nearby outbound route');assert(fork.elements['#bb-map-route'].children.some(o=>Number(o.value)===branchId),'the chosen branch is available');fork.elements['#bb-map-route'].value=String(branchId);fork.fire('bb-map-route','change');fork.fire('bb-map-travel');assert.equal(fork.read().maps.activeId,third,'selected route reaches chosen map');
console.log('PASS: multiple independent maps, shared characters, NPC/damage persistence, placement validation, two-way/one-way links, 3D preview/return, safe portal travel and debounce, collection undo/redo, save/reload/legacy migration, atomic malformed imports and cascade unlink/removal.');
