// Generated by scripts/extract-characters.mjs from v68's StudioMotion routines (P3.5).

import { Clip } from '../../core/schema';
import armCircles from './arm-circles.json';
import backKick from './back-kick.json';
import baseballCatch from './baseball-catch.json';
import baseballPitch from './baseball-pitch.json';
import baseballSwing from './baseball-swing.json';
import basketDribble from './basket-dribble.json';
import basketPass from './basket-pass.json';
import basketShot from './basket-shot.json';
import bicepsCurl from './biceps-curl.json';
import block from './block.json';
import chair from './chair.json';
import cobra from './cobra.json';
import dodge from './dodge.json';
import { EMOTE_CLIPS } from './emotes';
import frontKick from './front-kick.json';
import highKnees from './high-knees.json';
import hockeyHandle from './hockey-handle.json';
import hockeySave from './hockey-save.json';
import hockeySlapshot from './hockey-slapshot.json';
import hook from './hook.json';
import jabCross from './jab-cross.json';
import jumpingJacks from './jumping-jacks.json';
import kneeStrike from './knee-strike.json';
import lunges from './lunges.json';
import mountain from './mountain.json';
import plank from './plank.json';
import proneHipRock from './prone-hip-rock.json';
import pushUp from './push-up.json';
import roundhouse from './roundhouse.json';
import seatedTwist from './seated-twist.json';
import sideBend from './side-bend.json';
import sideKick from './side-kick.json';
import sitUp from './sit-up.json';
import soccerDribble from './soccer-dribble.json';
import soccerPass from './soccer-pass.json';
import soccerShot from './soccer-shot.json';
import squat from './squat.json';
import standingPelvicTilt from './standing-pelvic-tilt.json';
import tree from './tree.json';
import uppercut from './uppercut.json';
import volleyBump from './volley-bump.json';
import volleySet from './volley-set.json';
import volleySpike from './volley-spike.json';
import warrior from './warrior.json';

const RAW: Record<string, unknown> = {
  'arm-circles': armCircles,
  'back-kick': backKick,
  'baseball-catch': baseballCatch,
  'baseball-pitch': baseballPitch,
  'baseball-swing': baseballSwing,
  'basket-dribble': basketDribble,
  'basket-pass': basketPass,
  'basket-shot': basketShot,
  'biceps-curl': bicepsCurl,
  block: block,
  chair: chair,
  cobra: cobra,
  dodge: dodge,
  'front-kick': frontKick,
  'high-knees': highKnees,
  'hockey-handle': hockeyHandle,
  'hockey-save': hockeySave,
  'hockey-slapshot': hockeySlapshot,
  hook: hook,
  'jab-cross': jabCross,
  'jumping-jacks': jumpingJacks,
  'knee-strike': kneeStrike,
  lunges: lunges,
  mountain: mountain,
  plank: plank,
  'prone-hip-rock': proneHipRock,
  'push-up': pushUp,
  roundhouse: roundhouse,
  'seated-twist': seatedTwist,
  'side-bend': sideBend,
  'side-kick': sideKick,
  'sit-up': sitUp,
  'soccer-dribble': soccerDribble,
  'soccer-pass': soccerPass,
  'soccer-shot': soccerShot,
  squat: squat,
  'standing-pelvic-tilt': standingPelvicTilt,
  tree: tree,
  uppercut: uppercut,
  'volley-bump': volleyBump,
  'volley-set': volleySet,
  'volley-spike': volleySpike,
  warrior: warrior,
};

/** v68's routines (yoga, exercise, fighting, sports) as keyframe clips. */
export const BUILTIN_CLIPS: readonly Clip[] = [
  ...Object.values(RAW).map((raw) => Clip.parse(raw)),
  ...EMOTE_CLIPS.map((c) => Clip.parse(c)),
];

export const builtinClip = (id: string) => BUILTIN_CLIPS.find((c) => c.id === id) ?? null;
